### ISSUE TITLE
Can't activate caldera form

### ISSUE THREAD

**Issue by sventaf** [rupok/essential-addons-for-elementor-lite#1]
hello, 

I added EA and caldera form styler for elementor, before realising the second one is already included in the main pack. So i got rid of the extra styler and now i can't activate caldera in EA settings. It switchs on, i save settings but when i reload the page caldera is still turned off.

How can i activate it please

thanks

**Comment by rupok** [comment]
Hello @sventaf

It should not happen. Can you install a fresh copy of the plugin? If the issue still persists, you can initiate a live chat at wpdeveloper.net and someone will assist you.

Cheers!
