### ISSUE TITLE
Elementor page will not load

### ISSUE THREAD

**Issue by Slontje** [rupok/essential-addons-for-elementor-lite#114]
Since the latest elementor pro update I can't edit my pages. need to turn off the essential add ons pro plugin.

**Comment by Slontje** [comment]
Is there already a fix coming for this problem?

**Comment by russ00783** [comment]
still not opening elementor

**Comment by Slontje** [comment]
No still not opening. But now it only happens when elementor pro is activated.
When I deactivate elementor pro it will open.
