### ISSUE TITLE
Lightbox & Modal saved templates content no longer working

### ISSUE THREAD

**Issue by jasieem** [rupok/essential-addons-for-elementor-lite#115]
After updating the Elementor Pro plugin to 2.2.3, the lightbox that was using Essential Addons is no longer working. It will no longer pull the lightbox up correctly with an external trigger. The content for the lightbox is also now being shown on the webpage as if normal content without any "trigger" for the actual lightbox to show up.

**Comment by eurekaprinters** [comment]
Anyone have an answer to this major issue? Every page of our business website is now showing this issue with the lightbox content showing on the page as normal content.
