### ISSUE TITLE
addons plugnin making elementor crash

### ISSUE THREAD

**Issue by chmodx5** [rupok/essential-addons-for-elementor-lite#116]
activating this on my server causes elementor not to load/crash

**Comment by Magnifiquehomes** [comment]
We have the same issue. Elementor crashes with the add on! 
Deactivated all the other plug-ins so we know its not a compatibility error.

**Comment by embertech1** [comment]
White Screen of Death after updating Elementor to newest version when Essential Addons Pro for Elementor Pro is enabled, but if I just use Essential Addons free version it works ok.
