### ISSUE TITLE
Using the "Flexible Elementor Panel" the EA Widget Panel Icons don't stack correctly

### ISSUE THREAD

**Issue by myBCN** [rupok/essential-addons-for-elementor-lite#129]
I use the Elementor "Flexible Elementor Panel" plugin. One of its features is that you can drag the width of the Panel. When doing so all the icons align to the with except the EA ones that seem to skip the locations of the disabled widget as per the picture below.

![download1](https://user-images.githubusercontent.com/46058999/50367300-8f9e1c00-057f-11e9-94c5-2b622a84b48a.jpg)

//Matthias

**Comment by sabuz** [comment]
@myBCN Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
