### ISSUE TITLE
Cannot redeclare control with same name

### ISSUE THREAD

**Issue by propsht** [rupok/essential-addons-for-elementor-lite#132]
I added block "ea post grid" setup category. When I checked the page I see the issue 
http://take.ms/gaoS9

Elementor \ Controls_Manager :: add_control_to_stack function was called incorrectly. Cannot redeclare control with the same name "eael_section_post__filters". More information can be found on the WordPress Debugging page. (This message was added in version 1.0.0.) In /opt/lampp/htdocs/triathlonmania/wp-includes/functions.php on line 4204

**Comment by sabuz** [comment]
@propsht Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.

**Comment by EhtuCom** [comment]
It's happening in 2023
