### ISSUE TITLE
EA Tooltip Tag-Problem

### ISSUE THREAD

**Issue by GudrunReeHeidt** [rupok/essential-addons-for-elementor-lite#133]
I just bought Essential Addons for Elementor. With EA Tooltip I have the following Problem:
If I format a Text in Content Setting it looks fine (see attached screenshot / left side).
On the website the text format tags are visible (see attached screenshot for example "<H2>").
Do you have any idea where the problem is?
I use the newest Elementor Pro Version 2.3.1 and EA Version Version 2.13.2.
Many thanks for your support,
Kind regards,
![fehler_tooltipelementor](https://user-images.githubusercontent.com/46605195/51048152-84606e00-15ca-11e9-990f-443fb926f520.jpg)
Gudrun

**Comment by sabuz** [comment]
@GudrunReeHeidt Upgrading to latest version should fix your issue. Cheers!
