### ISSUE TITLE
Error en la nueva actualización 22/01/2019

### ISSUE THREAD

**Issue by utuffasi** [rupok/essential-addons-for-elementor-lite#151]
El día 22-01-2019 el plugin Essential Addons for Elementor me pidió una actualización la cuan al hacerse ocasiono errores el el menú desplegable del de mi pagina web no se si este error se este presentando en todos los temas o solo en el de mi pagina, el tema instalado es el photograph. https://es.wordpress.org/themes/photograph podrían ayudarme a resolver este problema ya que tengo varios bloques con este plugin y por el momento tuve que desactivarlo.

**Comment by sabuz** [comment]
@utuffasi Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
