### ISSUE TITLE
ERROR: #1548324172 Plugin essential-addons-for-elementor-lite/essential_adons_elementor.php was automatically deactivated due to an error at Thu, 24 Jan 2019 10:02:52 +0000!  Error was: Call to undefined function get_plugins()

### ISSUE THREAD

**Issue by cyril31** [rupok/essential-addons-for-elementor-lite#158]
ERROR: #1548324172 Plugin essential-addons-for-elementor-lite/essential_adons_elementor.php was automatically deactivated due to an error at Thu, 24 Jan 2019 10:02:52 +0000! 
Error was: Call to undefined function get_plugins()

Elementor - deactivated already
elementor essential addon deleted already but error still showing up

**Comment by sabuz** [comment]
@cyril31 Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
