### ISSUE TITLE
when I activate essential-addons-elementor plugin I can't close images anymore

### ISSUE THREAD

**Issue by waleedismail** [rupok/essential-addons-for-elementor-lite#16]
https://wordpress.org/support/topic/cant-close-image-inside-tabs-widget/

i am using WPocean theme and elementor.
When I open an image in "tabs" widget linked to media file it opens but can't close it anymore unless I deactivate "essential-addons-elementor" plugin which fixes the problem. 

this is the link to my page: 

https://denizpenplastik.com/en/ps60-2/

is there a way to fix this issue without having to deactivate the plugin?

**Comment by waleedismail** [comment]
yes I tried disabling everything it didn't work sadly

**Comment by rupok** [comment]
You can try using this custom CSS : 

```
.dialog-type-lightbox {
	display: none !important;
}
```
Thanks!

**Comment by waleedismail** [comment]
where I should use this code? cause only pro version of elementor excepts CSS codes on widgets.

**Comment by waleedismail** [comment]
oh I used the custom CSS on Simple Custom CSS plugin and it worked! 

thank you Rupok u saved my day. I hope you will have a great day.
thanks again.

**Comment by waleedismail** [comment]
Damn, is started happening again when I used Image Accordion. :(

**Comment by rupok** [comment]
Hi @waleedismail 

You can use custom CSS within Customizer > Additional CSS without any plugin. And is it happening on the given page or another?

**Comment by waleedismail** [comment]
hi, yes I am still having this problem unfortunately.

**Comment by waleedismail** [comment]
the thing is, when I first used the code u gave me it stopped the issue but it returned after sometime. it doesn't happen every time I try it so it's a bit frustrating.

**Comment by waleedismail** [comment]
Update: 
when I add the code into Additional CSS it effects this particular page 
https://denizpenplastik.com/en/p806/

making the images inside the tabs unclickable. when I remove the code the image links work and opens lightbox normally.

**Comment by waleedismail** [comment]
so is there any hope ?
