### ISSUE TITLE
Issue with the header

### ISSUE THREAD

**Issue by qtndrs** [rupok/essential-addons-for-elementor-lite#164]
Hello, 

I have this message on my screen. I don't know what to do to fix it. 

![capture](https://user-images.githubusercontent.com/47117514/51853808-767c4e00-2329-11e9-9534-13733b1dab74.JPG)

Thank you.

**Comment by sabuz** [comment]
@qtndrs Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
