### ISSUE TITLE
Fancy Text cannot add item

### ISSUE THREAD

**Issue by suiluj** [rupok/essential-addons-for-elementor-lite#169]
When trying to add an new element to the fancy text strings nothing happens.

Console shows the following error:
```
Uncaught ReferenceError: eael_fancy_text_strings_text_field is not defined
```

**Comment by suiluj** [comment]
any updates on this topic?

**Comment by sabuz** [comment]
@suiluj Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
