### ISSUE TITLE
Asking to activate license when switch language with WPML

### ISSUE THREAD

**Issue by vgstef** [rupok/essential-addons-for-elementor-lite#171]
Hi!
I've updated to v2.14.2 and I still get asked to activate my licence. It happened each time I switch the language with WPML (French/English in the backend). Maybe a conflict? Or maybe your plugin doesn't recognize the new URL (WPML adds "&lang=en")? 

I just tried to activate the licence while in English (secondary language) and it stopped asking for the licence. Maybe it,s solved. I'll see in the coming days.

**Comment by Netzlichter** [comment]
Same here. It is happening again and again when you are switching the languages....

**Comment by stefanico** [comment]
+1 :'\
