### ISSUE TITLE
Update Failed: Download failed. Unauthorized

### ISSUE THREAD

**Issue by Heyamandar** [rupok/essential-addons-for-elementor-lite#172]
I'm having yet another issue with this plugin. Geez, what's going on? This is the 3rd issue in the last 2 weeks. I can't update, gives me this message: Update Failed: Download failed. Unauthorized

**Comment by rupok** [comment]
I assume you still don't have the latest version but you were supposed to update to latest last time. Please deactivate the license and activate again to get the update. You can also download manually from your wpdeveloper.net/account
