### ISSUE TITLE
EA Post Grid: Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name 

### ISSUE THREAD

**Issue by antcw** [rupok/essential-addons-for-elementor-lite#179]
Wordpress 5.0.3
Elementor 2.4.6
Essential Addons for Elementor 2.9.5
This error is the same after disabling all other plugins and using wordpress theme Twenty Nineteen

adding the widget to an elementor section generates many lines of notice warnings as above, going through many controls names. Full list below

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_section_post__filters". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_post_type". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_posts_ids". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_authors". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_category_ids". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_post_tag_ids". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_product_cat_ids". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eaeposts_product_tag_ids". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "post__not_in". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "posts_per_page". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "offset". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "orderby". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "order". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_section_post_timeline_layout". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_post_grid_columns". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "show_load_more". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "show_load_more_text". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_show_image". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "image_size". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_show_title". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_show_excerpt". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_excerpt_length". 

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "eael_show_meta".

Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name "meta_position".

**Comment by sabuz** [comment]
@antcw Upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
