### ISSUE TITLE
EA Offcanvas

### ISSUE THREAD

**Issue by claudesundae** [rupok/essential-addons-for-elementor-lite#180]
Hello, (This is my first post, please mind my 'noobish' etiquette)

I am here to report a bug for **EA Offcanvas Tool**; Whenever I use it in combination with Elementor Pro on any post, the page will scroll back up to the top while navigating the page. This bug is only for mobile users.

I know this is an issues because I recreated this bug on two separate projects of mine. Has anyone else come across this problem, if so I'd love to know how you revolved it.

-Claude Sundae

**Comment by sabuz** [comment]
@claudesundae Upgrading to latest version should fix your issue. If not feel free to report it again! We will investigate your issue in deep.
