### ISSUE TITLE
Issue with Essential Addons with elementor

### ISSUE THREAD

**Issue by Gavrafootball** [rupok/essential-addons-for-elementor-lite#206]
Hi, i wanted to report an annoying issue that i've for 4 days with my website gavraracing.altervista.org. The menu doesn't work properly because of the plugin essential addons for elementor, in particular seems that there's a conflict between the plugins NavMenu for elementor and essential addons for elementor. I can say that for sure cause i've disabled all the plugins and then activate once at time and the only one who give me problems is essential... Last week it worked all fine but like i said since Saturday i've this annoying issue probably after an update, i need this plugin cause i used it in the most part of my pages, it would be great if you can fix this issue as soon as possible cause now in my website is impossible to navigate and that's really frustrating. I thank you in advance for any help

**Comment by MrForged** [comment]
I am also having an issue related the the more recent update of Elementor not being compatible with Essentials. Its seem to affect just the Navmenu when set to sticky, there is a work around by adjusting all the Z-indexes for all the widgets on each page, but that;s a huge pain.

**Comment by anjika** [comment]
There seems also to be a conflict with ninja forms. When it is activated, the elementor page builder won't load and the web page that was built is missing the main content area...

**Comment by sabuz** [comment]
@Gavrafootball @MrForged @anjika Upgrading to latest version should fix all of your issues!

**Comment by sabuz** [comment]
Hi all!
We haven't actually heard back from you. I hope your issue has be resolved. If not, please upgrade to latest version. I'm closing this ticket for now. Feel free to reopen if you have issues.
