### ISSUE TITLE
Breaking Menu on Home Page

### ISSUE THREAD

**Issue by migomarketing** [rupok/essential-addons-for-elementor-lite#209]
My website - Flintsteelcsg.com menu stopped working on the home page only. I de-activated all my plugins and re-activated them one by one and found that the Essential Addons plug-in was the cause of the issue.

I am using the Astra theme with Elementor builder.

**Comment by sabuz** [comment]
@migomarketing Upgrading to latest version should fix your issue!

**Comment by sabuz** [comment]
@migomarketing We haven't actually heard back from you. I hope your issue has be resolved. If not, please upgrade to latest version. I'm closing this ticket for now. Feel free to reopen if you have issues.
