### ISSUE TITLE
None of my EA Widgets Appear When I View My Site in Firefox or Edge

### ISSUE THREAD

**Issue by harrismaurice** [rupok/essential-addons-for-elementor-lite#210]
I am building my Wordpress site in Chrome using Elementor. Looks beautiful...in Chrome. Absolutely none of my EA widgets display when I view the site in Firefox or Edge. For example, EA Accordion only shows a gray box in Firefox and Edge. Any ideas?

**Comment by sabuz** [comment]
@harrismaurice upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you have issues.
