### ISSUE TITLE
Essential Addons bug

### ISSUE THREAD

**Issue by KozzyOsbourne** [rupok/essential-addons-for-elementor-lite#218]
Elementor can't load widgets with active Essential Addons plugin....
It's doesn't work correctly(((

**Comment by hellworks** [comment]
me too

**Comment by sabuz** [comment]
@KozzyOsbourne @hellworks Please update to latest version and check!

**Comment by sagar2kul** [comment]
I just installed everything fresh, but it is still not working. Not able to laod widgets with active essential addons

**Comment by KozzyOsbourne** [comment]
I solved that trouble. 

--
Михаил Козин
www.козин.рус

**Comment by sabuz** [comment]
Hi All!
