### ISSUE TITLE
EA PostGrid load more images not loading properly

### ISSUE THREAD

**Issue by Deleyna** [rupok/essential-addons-for-elementor-lite#221]
I've noticed this in other plugins using masonry where images load and cause the masonry to break. Adding a redraw after all images have loaded has fixed it for me on my own code, but I don't really want to hack yours.
I'm attaching a screen grab. Do you have any suggestions for me?
![Capture](https://user-images.githubusercontent.com/4100767/54249423-61d0cf80-44fd-11e9-9493-db4437a2faa2.JPG)

**Comment by sabuz** [comment]
@Deleyna Upgrading to latest version should fix your issue!

**Comment by Deleyna** [comment]
Thank you. I'm excited to see the change. I'm not seeing it on the site yet, though. I have two plugins that are both labelled Essential Addons for Elementor. I believe that this is NOT the Sizzify one. The Sizzify one we've had to roll back to a previous version because of a PHP error, but yours shows as at the current version, I think.
![Capture2](https://user-images.githubusercontent.com/4100767/56392250-c90d2e00-61e5-11e9-9b77-3fb584872d94.JPG)


![Capture](https://user-images.githubusercontent.com/4100767/56392086-54d28a80-61e5-11e9-9ec5-4dafbbda2131.JPG)

Maybe the two are interfering with each other?

Thank you so much for looking into this. We love your plugin.

**Comment by sabuz** [comment]
@Deleyna I hope your issue has be resolved. If not, please upgrade to latest version. I'm closing this ticket for now. Feel free to reopen if you have issues.

**Comment by Deleyna** [comment]
I'm sorry, but this has not been resolved. Even with the current version, here is what I'm getting:
![image](https://user-images.githubusercontent.com/4100767/58710812-0ed71d80-8372-11e9-9ba3-284bab4b4aad.png)

**Comment by Deleyna** [comment]
It is not fixed as I've shown in the ticket...

**Comment by sabuz** [comment]
@Deleyna please contact us on live support on [our site](https://wpdeveloper.net/). We will do our best to fix your issue.
