### ISSUE TITLE
White Page after Upate

### ISSUE THREAD

**Issue by Taste-IT** [rupok/essential-addons-for-elementor-lite#236]
White Pages after Update Lite-Version today. Deactivating and all is fine. I only use the Price-Table.

**Comment by rupok** [comment]
Hi @Taste-IT 

Please re-install v2.9.9. Everything will be fine.

**Comment by Taste-IT** [comment]
Hi rupok,
thx - this works.

**Comment by rupok** [comment]
Hi @Taste-IT It would be great if you help us to find the issue you faced on your site. Would you mind sending the system info (Elementor > System Info) of your site? You can send from our website live chat if you don't want to attach here.

**Comment by Taste-IT** [comment]
Hi rupok,
and sorry for answering so late, but i was very very busy. Sure i can help:

> 
Operating System: | Linux |  
-- | -- | --
Software: | Apache/2.4.25 (Debian) |  
MySQL version: | Debian 9.6 v5.6.41-84.1 |  
PHP Version: | 7.2.15 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 72M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  
Elementor Library: | Connected

WP Multisite: | No |  
-- | -- | --
Max Upload Size: | 64 MB |  
Memory limit: | 256M |  
Permalink Structure: | /%postname%/ |  
Language: | de-DE |  
Timezone: | Europe/Berlin

Active Plugins |   |  
-- | -- | --
Caldera Forms - 1.8.3 | By Caldera Labs |  
Easy Updates Manager - 8.0.5 | By Easy Updates Manager Team |  
Elementor - 2.5.10 | By Elementor.com |  
Essential Addons for Elementor - 2.9.9 | By WPDeveloper |  
FooGallery - 1.6.17 | By FooPlugins |  
Ginger - EU Cookie Law - 4.2 | By Manafactory |  
Google XML Sitemaps - 4.1.0 | By Arne Brachhold |  
TinyMCE Advanced - 5.1.0 | By Andrew Ozz |  
WP Statistics - 12.6.2 | By VeronaLabs |  
WP Updates Notifier - 1.4.4 | By Scott Cariss

Theme |   |  
-- | -- | --
Name: | Twenty Seventeen |  
Version: | 2.1 |  
Author: | the WordPress team |  
Child Theme: | No

>

**Comment by rupok** [comment]
Hi @Taste-IT 

Thanks for providing the info. Would you please update to v2.10.1? Hopefully you won't face the issue.

Cheers!

**Comment by sabuz** [comment]
@Taste-IT I presume your issue was fixed. I'm closing this ticket for now. Please feel free to reopen it if you still have issues!
