### ISSUE TITLE
fatal error | on website peter-traa.com | using essential-addons-elementor

### ISSUE THREAD

**Issue by Schmidtworks** [rupok/essential-addons-for-elementor-lite#241]
Hi essential-addons-Team

I've got a problem on a managed website - peter-traa.com

Error-Logfiles showed me this information.
How can I solve this "fatal error"

See logfile extract:
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] Stack trace:
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] #0 /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-includes/class-wp-hook.php(286): Essential_Addons_Elementor->eael_add_elements(Object(Elementor\\Widgets_Manager))
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] #1 /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] #2 /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] #3 /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-content/plugins/elementor/includes/managers/widgets.php(99): do_action('elementor/widge...', Object(Elementor\\Widgets_Manager))
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] #4 /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-content/plugins/elementor/includes/managers/widgets.php(235): Elementor\\Widgets_Manager->init_widgets()
29.03.2019 09:28:46 peter-traa.com [client 94.79.19.0] #5 /mn in /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Elements.php on line 59
29.03.2019 09:32:07 peter-traa.com [client 94.79.19.0] PHP Fatal error:  Uncaught Error: Class '\\Essential_Addons_Elementor\\Elements\\' not found in /mnt/web418/c2/20/59369320/htdocs/WordPress_SecureMode_01/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Elements.php:59

Thanx for your fast feedback - via friedhelm@schmidt-works.de

**Comment by sabuz** [comment]
@Schmidtworks hope you're doing well! Please upgrade Essential Addons to v2.10.1 and hope this will fix your issue.

**Comment by sabuz** [comment]
@Schmidtworks We haven't actually heard back from you. I hope your issue has be resolved. If not, please upgrade to latest version. I'm closing this ticket for now. Feel free to reopen if you have issues.
