### ISSUE TITLE
Server Error (404 Not Found)

### ISSUE THREAD

**Issue by BakedMunchkin** [rupok/essential-addons-for-elementor-lite#242]
Using your EA Data Tables gives me this error.
Tried flushing permalinks disabling unused stuff from settings and clearing cache everywhere.
Sometimes it works sometimes it doesnt... Cant keep up with this $heep.
Fix it.

**Comment by rupok** [comment]
Hi @BakedMunchkin 

Would you kindly create a support ticket from https://wpdeveloper.net/support/ so we can assist you on this better? It's not something we could replicate or didn't get such report at all. So perhaps you are facing something related to your server or conflict with another plugin. If you provide a bit more information, it would help us to fix.

Thanks!
