### ISSUE TITLE
Essential Addons Settings

### ISSUE THREAD

**Issue by maestro65** [rupok/essential-addons-for-elementor-lite#245]
Warning: include(/home/pamytnik/pamytniki-kharkov.com.ua/www/wp-content/plugins/essential-addons-for-elementor-lite/vendor/composer/../../elements/Eael_Post_Grid.php): failed to open stream: No such file or directory in /home/pamytnik/pamytniki-kharkov.com.ua/www/wp-content/plugins/elementor-addon-widgets/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '/home/pamytnik/pamytniki-kharkov.com.ua/www/wp-content/plugins/essential-addons-for-elementor-lite/vendor/composer/../../elements/Eael_Post_Grid.php' for inclusion (include_path='.:/usr/local/pear/php56') in /home/pamytnik/pamytniki-kharkov.com.ua/www/wp-content/plugins/elementor-addon-widgets/vendor/composer/ClassLoader.php on line 412

Fatal error: Class '\Essential_Addons_Elementor\Elements\Eael_Post_Grid' not found in /home/pamytnik/pamytniki-kharkov.com.ua/www/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Elements.php on line 64

**Comment by rupok** [comment]
Hi @maestro65 please try re-installing the plugin.

**Comment by sabuz** [comment]
@maestro65 We haven't actually heard back from you. I hope your issue has be resolved. If not, please upgrade to latest version. I'm closing this ticket for now. Feel free to reopen if you have issues.
