### ISSUE TITLE
Notice: Trying to get property 'elements' of non-object in /home/content/n3pewpnaspod01_data03/20/42366920/html/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Generator.php on line 109

### ISSUE THREAD

**Issue by shadhk** [rupok/essential-addons-for-elementor-lite#249]
When I activated this plugin, got an Error multiple times on my website above the header. Please resolve this issue asap, so that I may use your plugin and get the benefit of this plugin. Please response asap. My theme is Astra + Elementor.

**Comment by Asif2BD** [comment]
@shadhk if possible share your system information from Elementor => System Info, copy paste that, and send in our support form - https://wpdeveloper.net/support/ (please don't share openly here.

And @sabuz I assigned this to you.

**Comment by sabuz** [comment]
@shadhk Could you please make sure that you're using v2.10.1?

**Comment by sabuz** [comment]
Hi @shadhk 

We have released a new version today. So, please update to the latest version and your issues should be resolved now.

If you still face any issue with the layout, simply just go to your WordPress dashboard. Then navigate to wp-admin -> Elementor -> Essential Addons -> Tools. Then, click on ‘Clear Cache’ button. It should fix it. Here’s the screenshot: https://prnt.sc/n78rdi

So, let me know how it goes. Thank you.

**Comment by shadhk** [comment]
Hi Nazmul,

Thanks for the update.
But still I face the same problem.
I am using Astra Theme with elementor.
Please kindly recheck essential-addons-elementor-lite's version with my
theme.
Please resolve this issue asap.


Thanks,

Shad Khan




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/13/19,
1:24:29 PM

**Comment by sabuz** [comment]
@shadhk Please contact us here: https://wpdeveloper.net/support/ so that we can investigate your problem deeply.

**Comment by sabuz** [comment]
@shadhk We haven't actually heard back from you. I hope your issue has be resolved. If not, please upgrade to latest version. I'm closing this ticket for now. Feel free to reopen if you have issues.
