### ISSUE TITLE
EA Filterable Gallery is showing up weird on live site.

### ISSUE THREAD

**Issue by tisbrat** [rupok/essential-addons-for-elementor-lite#254]
Hi, I am currenting building a website and the EA Filterable Gallery has recently been showing up weird on the live page. Image 1 is how it use to look before and in the editable state in elementor and the second image is how it looks currently on the live website.

![1](https://user-images.githubusercontent.com/22814162/55511985-92e97f00-5627-11e9-9bbb-2c3a831661d0.PNG)

![Capture2](https://user-images.githubusercontent.com/22814162/55512003-9d0b7d80-5627-11e9-8365-b59ad933fc65.PNG)

**Comment by sabuz** [comment]
Hi @tisbrat 
We have released a new version today. So, please update to the latest version and your issues should be resolved now.

If you still face any issue with the layout, simply just go to your WordPress dashboard. Then navigate to wp-admin -> Elementor -> Essential Addons -> Tools. Then, click on ‘Clear Cache’ button. It should fix it. Here’s the screenshot: https://prnt.sc/n78rdi

So, let me know how it goes. Thank you.

**Comment by tisbrat** [comment]
Thanks the update fixed the major problem but I still see a slight glitch if I have two filterable galleries on one page. The second gallery is out of whack. Below is an image of the second gallery when editing within Elementor and the second image is what it looks like on the live page. I also cleared the cache to see if that will help but it didn't do anything. 
![Capture3](https://user-images.githubusercontent.com/22814162/55651403-19c86400-57ae-11e9-83ae-3c65043c2b27.PNG)
![Capture4](https://user-images.githubusercontent.com/22814162/55651411-1f25ae80-57ae-11e9-8605-7f5a77753b46.PNG)

**Comment by sabuz** [comment]
@tisbrat upgrading to latest version, and clearing cache should fix your issue. Let me know if you've any issues.

**Comment by tisbrat** [comment]
Hi, I did everything as stated, updating and clearing the cache, but no changes. It still looks the same. I think something is affecting the second filterable gallery. No matter which gallery is placed second on the same page it looks like the above image.

**Comment by sabuz** [comment]
@tisbrat Please contact us from here: https://wpdeveloper.net/support/. Don't forget to mention your github issue id.
