### ISSUE TITLE
EA Advanced Accordion not working properly after the latest update

### ISSUE THREAD

**Issue by elwolfinho** [rupok/essential-addons-for-elementor-lite#255]
Hello, after the last update something terribly went wrong with the EA Advanced Accordion widget, since all tabs are opened and style is not accepted, although it looks fine in the builder, when i load the page in the browser it is broken. Please help.

Link: moraph.com

**Comment by sabuz** [comment]
Hi, there. We have released a new version today. So, please update to the latest version and your issues should be resolved now.

If you still face any issue with the layout, simply just go to your WordPress dashboard. Then navigate to wp-admin -> Elementor -> Essential Addons -> Tools. Then, click on ‘Clear Cache’ button. It should fix it. Here’s the screenshot: https://prnt.sc/n78rdi

So, let me know how it goes. Thank you.

**Comment by elwolfinho** [comment]
Hello!

Thanks, I've tried but Accordions still don't work. Fortunately however,
i've downloaded the previous version and it works fine. Thank you very much.

**Comment by sabuz** [comment]
Please contact us through here so that we can investigate this issue: http://wpdeveloper.net/support/

**Comment by elwolfinho** [comment]
I contacted there previously, they have said to try the new version and if
is not working, to download the previous. I've tried, the new version still
has the same bug with Accordions, i've downloaded the one before and it was
all good. Thank you very much.

**Comment by sabuz** [comment]
@elwolfinho upgrading to latest version, and clearing cache should fix your issue. Let me know if you've any issues.

**Comment by sabuz** [comment]
@elwolfinho I presume that your issue has been fixed. Closing the ticket, feel free to reopen if you've issue.
