### ISSUE TITLE
Filterable Gallery Issues

### ISSUE THREAD

**Issue by anthonyryanrusso** [rupok/essential-addons-for-elementor-lite#267]
Issue 1) If you have multiple filterable controls such as, weddings, sports, events and you go to one of these filterable controls on the frontend and try to view the images they aren't there yet (which is ok since the items are probably in pages, hence the load more button) BUT when you hit load more, nothing happens until you've loaded all of the items, then they all appear at once.

Issue 2) Once they all appear in that certain filterable control and then you click the load more button one more time, the load more button disappears since there are no more items in that category (which is ok).  However, if you then go back to "all" the load more button is still missing even though ALL items have not loaded.

Issue 3) When using the gallery zoom + slider where it cycles through the images it should only show images in that certain category but currently it will show all images from all categories if you keep cycling through them.

**Comment by rince1984** [comment]
Issue 4) Filterable controls are shown among themselves and they are not clickable (since the last elementor update 2.5.13)

**Comment by sabuz** [comment]
Thank you for informing us about this. We will work on it and fix this in the future.
