### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by javaunm** [rupok/essential-addons-for-elementor-lite#268]
Since the recent update, with Elementor enabled, Elementor Pro and this plugin - attempting to utilize the Customize.php portion of my site throws a HTTP ERROR 500. 

I am using ONLY the above three plugins in a staging environment to troubleshoot the issues. However, if I disable by theme, Flatsome 3.8.1 by UX-Themes it will work fine.

I'm unsure if there is a conflict with the theme or the recent update is causing a conflict however I would appreciate if this was resolved in a timely fashion.

Thank you!

**Comment by sabuz** [comment]
@javaunm Upgrading to latest version should fix your issue!

**Comment by sabuz** [comment]
@javaunm We haven't actually heard back from you. I presume that your issue was fixed. So I'm closing this ticket for now. Feel free to reopen if you still have problems.
