### ISSUE TITLE
Found issue in EA Flip box

### ISSUE THREAD

**Issue by SanjuSingha** [rupok/essential-addons-for-elementor-lite#269]
Essential Add-ons element flip box crashes when opened in website preview. It works properly in elementor but crashes in website preview. The front and back side of the flip box appears together in preview.
![Screenshot_73](https://user-images.githubusercontent.com/49482613/55877378-7f09c400-5bb7-11e9-9287-3f485df2a497.jpg)
Should appear like this:

![Screenshot_74](https://user-images.githubusercontent.com/49482613/55877432-98127500-5bb7-11e9-9726-cf369724d7a8.jpg)

**Comment by sabuz** [comment]
@SanjuSingha Can you please check that you've set permission to 755 for this folder 'wp-content/uploads/essential-addons-elementor'?

**Comment by sabuz** [comment]
@SanjuSingha I presume your issue was fixed. If not upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you are facing problems.
