### ISSUE TITLE
Essential Addons for Elementor - issue with cache

### ISSUE THREAD

**Issue by sdq1980** [rupok/essential-addons-for-elementor-lite#270]

**Comment by sabuz** [comment]
@sdq1980 Please describe your problem in details

**Comment by sdq1980** [comment]
The CSS style will not work unless you clear the cache. Then the CSS style
reverts back from not applying.

**Comment by sabuz** [comment]
@sdq1980 upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you are facing problems.
