### ISSUE TITLE
Post Grid Load More is not loading

### ISSUE THREAD

**Issue by Chunen2000** [rupok/essential-addons-for-elementor-lite#271]
Hello, i want to report a issue that i faced wile creating my webside. the Load More button is not loading more posts when i click on it. I didn't notice it before i write more than the post per page number. 
The button stays in a Loading motion for eternal period when i click on it, and if i click in somewere else it stops.

![image](https://user-images.githubusercontent.com/49578179/56074408-2b9aa000-5d88-11e9-8825-702beac14604.png)

**Comment by sabuz** [comment]
Please contact us from here https://wpdeveloper.net/support/ so that we can discuss in details and investigate your problems!

**Comment by sabuz** [comment]
@Chunen2000 upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you are facing problems.
