### ISSUE TITLE
Essential Addons for elementor - issue with Post Timeline Widget

### ISSUE THREAD

**Issue by dylangoh80** [rupok/essential-addons-for-elementor-lite#273]
Hello Guys, I building a category specific template for my wordpress blog.

Using Astra Theme + Elementor Pro + Essential Add on For Elementor

I used EA Post Timeline to build it and look like picture number one. Everything just ok.

But after published, it's totally different things (Refer picture 2)

Anyone have idea what could be happen?

Thank you in advance

![Capture](https://user-images.githubusercontent.com/49601830/56087499-25e3ae00-5e9f-11e9-9170-9804550c7b92.JPG)
![Capture 2](https://user-images.githubusercontent.com/49601830/56087502-2a0fcb80-5e9f-11e9-90c4-f94fcff07962.JPG)

**Comment by sabuz** [comment]
@dylangoh80 Upgrading to latest version should fix this.

**Comment by sabuz** [comment]
@dylangoh80 I presume that your issue was fixed. So I'm closing this ticket for now. Feel free to reopen if you are facing problems.
