### ISSUE TITLE
Post Grid not publishing correctly

### ISSUE THREAD

**Issue by andiepeart** [rupok/essential-addons-for-elementor-lite#280]
Hello,

Post grid is not publishing correctly. It looks perfect when I am doing the design, but when I publish all of the formatting goes away. 

All of my plugins and wordpress are up to date as of today. 
![EA1](https://user-images.githubusercontent.com/49759625/56372288-b4706c00-61cc-11e9-8de7-7b8bd2f1ee31.jpeg)
![EA2](https://user-images.githubusercontent.com/49759625/56372289-b4706c00-61cc-11e9-9ece-491d4d8582b8.jpeg)

**Comment by sabuz** [comment]
@andiepeart Please contact us here: https://wpdeveloper.net/support/ so that we can assist you

**Comment by sabuz** [comment]
@andiepeart upgrading to latest version should fix your issue. I'm closing this ticket for now. Feel free to reopen if you are facing problems.
