### ISSUE TITLE
Fancy Text cannot be edited

### ISSUE THREAD

**Issue by werozen** [rupok/essential-addons-for-elementor-lite#281]
After set 2 fancy text boxes on the same page they cannot be edited anymore, edit area remains blank, I already tried another web browser, clearing the cache and even reboot my computer.

After try to rebuild it again from scratch I noticed it began to behave buggier after I tried to add a new item on the list.

![2019-04-18 22_05_07-Elementor _ Bienvenido a Tecniclub](https://user-images.githubusercontent.com/1770293/56387970-13ae9a80-6226-11e9-85a8-130f5e4b0fd5.png)

![2019-04-18 21_56_45-Elementor _ Bienvenido a Tecniclub](https://user-images.githubusercontent.com/1770293/56387625-1492fc80-6225-11e9-8924-501abdbc62cf.png)

**Comment by mr-mahfuz** [comment]
Hi there,
We got your issue and fixed it. Please wait for the next update.

**Comment by sabuz** [comment]
@werozen I presume that your problem was fixed. So I'm closing this ticket. Feel free to reopen if you are facing problems.
