### ISSUE TITLE
Elements are not loading

### ISSUE THREAD

**Issue by jhchandler** [rupok/essential-addons-for-elementor-lite#282]
EA will not load with anything more than Contact Form 7 selection active.  Based on other people's problem with this plugin, it would seem the developer should include a list of required plugins needed for this plugin to work properly.  
I have one website that was pre-loaded with plugins and theme.  I duplicated this in a separate website so I can transition from MS Expressions to WP, however, despite having the same theme and plugins installed, this site will not load the Essential Addons for Elimenator.  So far, I have spent 5 hours trying to get this to work, so I am loosing money because of this app as it wastes my day.

**Comment by mr-mahfuz** [comment]
Hi, there. I am really sorry to hear about the issue you are facing. Is there any particular error you are seeing? Can you please provide me any screenshots? Can you please try increasing your PHP Memory Limit to 512M? Let me know how it goes. If you have any further issues, you can also email us here: support@wpdeveloper.net and provide us a temporary admin access of your site. We will try to resolve it as soon as possible. Thank you.
