### ISSUE TITLE
EA Post Timeline/Grid Error

### ISSUE THREAD

**Issue by gonzalochica** [rupok/essential-addons-for-elementor-lite#283]
What happens with ea post timeline/grid?

In the editor it shows correctly and then in the website (PC, Tablet and phone) it displays worngly. I tried removing caché but that's not the problem.

The plugin is also in the latest version.

![image](https://user-images.githubusercontent.com/44378094/56565952-d5acd000-65b1-11e9-8a2a-f18458a03f48.png)

![image](https://user-images.githubusercontent.com/44378094/56566114-36d4a380-65b2-11e9-8ee7-51f197308d95.png)

**Comment by sabuz** [comment]
Please contact us here: https://wpdeveloper.net/support/ so that we can assist you

**Comment by sabuz** [comment]
Hi @gonzalochica
We haven't actually heard back from you. Did you upgrade to latest version? Can you please tell us whether your issue is fixed or not?
I'm closing this ticket for now, feel free to reopen it again if you still have issues.
