### ISSUE TITLE
(blocked:mixed-content) BUG due dont check HTTP protocol after print EA css file

### ISSUE THREAD

**Issue by pabloaugusto** [rupok/essential-addons-for-elementor-lite#284]
backgound: 

- I'm testing free version.
- just instaled and reinstaled many times
- Tested on a fresh wordpress to confirm

The EA css is been loaded without verify the web protocol. Always use http. My site is https, so, when you try to load the css file and dont put https browsers block due security.

EA is printing this css file http://mydomain.com/wp-content/uploads/essential-addons-elementor/eael-post-5677.min.css?ver=2.10.4

Note that EA system use HTTP anda not HTTPs, but my sate is HTTPs, so this generate security issue witho chrome and other browsers, the css is blocked (dont load) and component style crashes...

In the inspector the error is displayed at NETWORR tab at chrome 
(blocked:mixed-content)

**Comment by sabuz** [comment]
Hi, there!We are really sorry for the inconvenience caused. However, we have already fixed this from our side and we are going to release a new version hopefully by tomorrow. Everything should be resolved then.
