### ISSUE TITLE
eael.min.css not charged

### ISSUE THREAD

**Issue by sandrocirlini** [rupok/essential-addons-for-elementor-lite#287]
the plugin, in elementor editor mode I setted Center value in Form Alignment...
 In elementor editor mode I view the form correctly aligned in center, but out editor mode the alignment remained to the left.
this because in editor mode eael.min.css is charged, but in normal mode isn't charged

**if I clear the cache with "clear cache" in tools, the first time I refresh the page in normal mode(not elementor editor mode), it work correctly, but if refresh the page another time, it does not work anymore (remain aligned to the left and eael.min.css not charged)**

**Comment by sandrocirlini** [comment]
if I clear the cache with "clear cache" in tools, the first time I refresh the page in normal mode(not elementor editor mode), it work correctly, but if refresh the page another time, it does not work anymore (remain aligned to the left and eael.min.css not charged)

**Comment by sabuz** [comment]
Please contact us here: https://wpdeveloper.net/support/ so that we can assist you.

**Comment by JoeHana** [comment]
Having the same issue here. Some basic styles from EA are not loaded properly. I needed to clear the cache with the tools from EA and after the first visit it worked, but after another refresh the CSS was missing again.

**Comment by sandrocirlini** [comment]
I solved the problem with a poppies of  rules on external css

Il mer 29 mag 2019, 22:51 Joe Hana <notifications@github.com> ha scritto:

**Comment by JoeHana** [comment]
Not sure what you mean but I'm glad you solved it for you. However, this obviously needs to be addressed generally I think. Here is an error I get and I think its most likely connected to this issue described here.

Warning: file_get_contents(/www/htdocs/xxxxxx/xxx/xxx/_live/wp-content/plugins/essential-addons-elementor/assets/front-end/css/section-parallax/index.min.css): failed to open stream: No such file or directory in /www/htdocs/xxxxxx/xxx/xxx/_live/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 28

It obviously belongs to the parallax effect, but this leads also to the conclusion that there is a general issue with the CSS loading.

**Comment by sabuz** [comment]
@JoeHana This problem was fixed earlier. Please make sure that you're using latest version of the plugin, and let me know if the issue has been fixed or not.

**Comment by JoeHana** [comment]
Running EA 3.0.2 an EA Pro 3.0.3 - but still have this issue with the CSS. Already tested in other browsers as well as I've also multiple times cleared caching (browser and server) - but no success. Same issue as described above.

**Comment by sabuz** [comment]
@JoeHana can you please contact [support](https://wpdeveloper.net/support/) for deep investigation?

**Comment by JoeHana** [comment]
Issue is still here...guess it hasn't been adressed now? When do you think this will be resolved?

**Comment by rupok** [comment]
Hi @JoeHana are you still facing the issue? Can you try clear cache from **Essential Addon > Tools** again and check?

**Comment by JoeHana** [comment]
Yes, I already updated to the latest versions and cleared all available caches...from EA, from WP Rocket, Browser Cache...

**Comment by JoeHana** [comment]
So, I have now disabled WP Rocket to ensure there is not another potential source for this issue.

I then cleared the Cache from the EA Tools.
I refreshed the website and everything looks good
I refreshed the website again and the issue is here again.

Not sure what else I could do? Pretty limited here since the website is already live...

**Comment by sabuz** [comment]
@JoeHana @JoeHana 
Please contact us via live support from https://wpdeveloper.net
We will investigate your issue deeply, and will try our best to resolve your issue!

**Comment by mbautista** [comment]
Hello,
We have the same issue :
- PHP 7.0
- WordPress  5.2.2
- Elementor 2.5.15
- Elementor Pro 2.5.9
- Essentails Addons for Elementor 3.1.13

We setup a EA Filterable Gallery without Layout = Masonry
All works good in editor 
Page loads great in the front-office in the first time
When we refresh the page, eael.min.css AND eael.min.js are not loaded anymore and gallery is broken.
It still works in the editor
We can make it work again on the front by clearing the EA cache in the admin (Essential Addons > Tools > Clear cache)
But it breaks again when we refresh the page.

Would anyone have a quick fix for this please ?
Thank you :)

**Comment by mbautista** [comment]
Hello,
I found a quick and dirty fix in `/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Enqueue.php`, line 101 :

I replaced : 
`if ($this->has_cache_files($post_type, $queried_object)) {`
by 
`if (false && $this->has_cache_files($post_type, $queried_object)) {`

It now works good on my website, but I suppose it will break something else on other configurations...

Mathieu.

**Comment by sabuz** [comment]
@mbautista Please contact our live support and refer this issue id

**Comment by JoeHana** [comment]
Not sure why, but this issue is now here again? Please fix it again. Thanks

**Comment by mbautista** [comment]
This problem may be related to the `EAEL_ASSET_URL` constant : it contains a URL like '/wp-content/uploads/...' but this URL is not valid on a WordPress Multisite setup, it should be something like '/wp-content/blogs.dir/BLOG_ID/...'.

I think this constant should be replaced by https://developer.wordpress.org/reference/functions/wp_upload_dir/

We have not tried to fix this constant, for now we ensure not to use it, around line 110 : 
```
            // enqueue scripts
            // IRCF : Never use EAEL_ASSET_URL
            if (false && $this->has_cache_files()) {
                $css_file = EAEL_ASSET_URL . '/eael.min.css';
                $js_file = EAEL_ASSET_URL . '/eael.min.js';
            } else {
                $css_file = EAEL_PLUGIN_URL . '/assets/front-end/css/eael.min.css';
                $js_file = EAEL_PLUGIN_URL . '/assets/front-end/js/eael.min.js';
            }
```

And around line 172 : 
```
        // IRCF : Never use EAEL_ASSET_URL
        if (false && $this->has_cache_files($post_type, $queried_object)) {
            $css_file = EAEL_ASSET_URL . '/eael-' . $post_type . '-' . $queried_object . '.min.css';
            $js_file = EAEL_ASSET_URL . '/eael-' . $post_type . '-' . $queried_object . '.min.js';
        } else {
            $css_file = EAEL_PLUGIN_URL . 'assets/front-end/css/eael.min.css';
            $js_file = EAEL_PLUGIN_URL . 'assets/front-end/js/eael.min.js';
        }
```

**Comment by sabuz** [comment]
@mbautista Thank you for your comments. We've already fixed the issue you're facing. Please wait for the next update.
