### ISSUE TITLE
EA Fancy Text

### ISSUE THREAD

**Issue by FriisFjordside** [rupok/essential-addons-for-elementor-lite#295]
I have experienced twice that the fancy text just shows all the fancy text listed not animating. 
First time i had to update some plugins, but this around theres no updates.

**Comment by sabuz** [comment]
Please follow the docs and let me know https://essential-addons.com/elementor/docs/faq/increase-memory-limit-wordpress/

**Comment by sabuz** [comment]
@FriisFjordside Please upgrade to latest version and let me know if your issue has been fixed or not. I'm closing the ticket for now. Feel free to reopen it if your issue has not been fixed yet.
