### ISSUE TITLE
Essential addons is causin issues to Elementor!

### ISSUE THREAD

**Issue by heronhebling** [rupok/essential-addons-for-elementor-lite#296]
Essential addons is causing elementor plugin area infinite loading. As sonn as i activate the plugin, the issue starts:
![image](https://user-images.githubusercontent.com/50703515/57852274-1cf53d80-77b9-11e9-9662-618fc9da833e.png)

**Comment by sabuz** [comment]
Please try this first: https://essential-addons.com/elementor/docs/faq/increase-memory-limit-wordpress/
Let me know if your problem is solved or not.

**Comment by sabuz** [comment]
Hi @heronhebling 
Has your problem solved? Please let me know. If not, please try to upgrade to latest version.
Since you didn't reply for a while, I'm going to close the ticket. Still if you have any issue, feel free to reopen it.
