### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by zaji** [rupok/essential-addons-for-elementor-lite#297]
Thought it was one of the other Elementor plugins, but I deactivated all and turned on all one by one. It is definitely your plugin that won't allow the Elementor widget sidebar to load. The blue circle just keeps spinning and it never loads. When I deactivate it, the sidebar widgest while in Elementor loads. Turn it on again, it doesn't load. Widgets are grayed out and nothing happens. Deactivate, all is well.

<img width="295" alt="Screen Shot 2019-05-20 at 12 02 30 AM" src="https://user-images.githubusercontent.com/7225437/57995916-97acaa00-7a92-11e9-9e4f-0942a4b1b5d7.png">

**Comment by rupok** [comment]
Hi @zaji It might happen if you don't have enough resource on your server. You can try increasing your memory.

**Comment by zaji** [comment]
I see. Well only your plugin won’t work. All others work and i have nearly 2 dozen plugins. 



namaste & sawubona, 
zaji
thezaji.com

On May 20, 2019, at 6:06 AM, Nazmul H. Rupok <notifications@github.com> wrote:

Hi @zaji It might happen if you don't have enough resource on your server. You can try increasing your memory.

**Comment by zaji** [comment]
> Hi @zaji It might happen if you don't have enough resource on your server. You can try increasing your memory.

Went through and deactivated plugins. It's Ninja Forms plugin that is causing the issue. Tried 3 times activating and deactivating it and your plugin didn't like it each time and kept spinning while Ninja Forms was activated. Thought you'd like to know about this conflict. I don't really need to use Ninja Forms anymore, so will be deleting it.

**Comment by sabuz** [comment]
@zaji Thanks for noticing the issue. It's not about conflict with our plugin. It's about a php notice that resides in Ninja forms.
