### ISSUE TITLE
Plugin setting look bad on RTL site

### ISSUE THREAD

**Issue by mstudioIL** [rupok/essential-addons-for-elementor-lite#303]
The layout is looking bad, all the icon are huge and setting not align right
![screen](https://user-images.githubusercontent.com/3463395/58024737-8f4c8180-7b1b-11e9-9779-580a4b53f0af.jpg)

**Comment by sabuz** [comment]
Is it okay for LTR lang?

**Comment by mstudioIL** [comment]
I work, but I think some of elements are not align to the right

**Comment by sabuz** [comment]
Thank you for informing us about this. We will work on it and fix this in the future.
