### ISSUE TITLE
pricing table with data entered, but does not appear on the page after updating WP

### ISSUE THREAD

**Issue by osmar2108** [rupok/essential-addons-for-elementor-lite#312]

**Comment by osmar2108** [comment]
I was using the EA Pricing table tool, and after updating WordPress, the data in the table does not appear on the main page.

**Comment by osmar2108** [comment]
> I was using the EA Pricing table tool, and after updating WordPress, the data in the table does not appear on the main page.

Okay. Problem solved. In Pricing style, during the design I chose style 3, which after the update is only valid for pro signature.

**Comment by sabuz** [comment]
Cheers!
