### ISSUE TITLE
"Tabs Title" <li> property carrying over to "Tabs Content" body

### ISSUE THREAD

**Issue by mylimoproject** [rupok/essential-addons-for-elementor-lite#313]
Whenever using the TABS widget and using a "list" tab's on content body, the <li> property get inherited by any list used on content section. To solve this, I have to add a custom css class as follows: 

.eael-tabs-content li {display: block; padding-top:0px; padding-bottom:5px !important}

This is an easy fix. Please correct.
**Note:** Just purchased PRO license 
https://airportspickup.com
https://airportspickup.com/black-car-service-stamford-ct-limo-jfk-airport-shuttle-lga-ewr-taxi-service/

**Comment by mr-mahfuz** [comment]
Hello mylimoproject,
Thank you for your suggestion, we'll keep that in our mind.
