### ISSUE TITLE
Installing essential addons pro 3.0 breaks elementor pro plugins

### ISSUE THREAD

**Issue by haniobaid** [rupok/essential-addons-for-elementor-lite#314]
I'm currently running EA pro 2.15 without problems with elementor 2.5.15 (latest) elementor pro 2.5.8 (latest) and wordpress 5.2.1 at https://www.cloudtheapp.com

Basically when I install the 3.0 Essential addons pro update, everything breaks.

The parallax stars effect on my homepage stops. The unfold widgets on the same page (scroll down) become plain truncated text with no unfold, the Header animation on my solutions page no longer animates, the Ken burns effect on the headers of the about and contact us pages no longer animate.

**Comment by sabuz** [comment]
Please upgrade to latest version(3.0.3) and let me know if this has been fixed or not.

**Comment by haniobaid** [comment]
Thanks. I will on sunday, let me know if you need any specific info in case it didn't work so i can get it before rollback 

On May 30, 2019, at 9:36 AM, Nazmul Islam Sabuz <notifications@github.com> wrote:

Please upgrade to latest version(3.0.3) and let me know if this has been fixed or not.

**Comment by haniobaid** [comment]
Hello,
 
I tried to install it today since elementor, elementor pro were also updated.
 
Unfortunately, the same thing happened.
 
Basically, when I update, it says that I need to install the basic plugin as well although the basic one it wants to install is 3.0.2, and once that happens all the elementor plugins freeze.
 
Thanks,
 
Hani

**Comment by haniobaid** [comment]
Wordpress emailed the error details when I tried 3.0.3

 

It seems to be related to the update checks.

 

 

Error Details

=============

An error of type E_ERROR was caused in line 44 of the file /home/cloudthe/public_html/wp-content/plugins/bdthemes-element-pack/includes/updater/plugin-update-checker/Puc/v4p5/Vcs/PluginUpdateChecker.php. Error message: Uncaught Error: Class 'Puc_v4p5_Plugin_Info' not found in /home/cloudthe/public_html/wp-content/plugins/bdthemes-element-pack/includes/updater/plugin-update-checker/Puc/v4p5/Vcs/PluginUpdateChecker.php:44

Stack trace:

#0 /home/cloudthe/public_html/wp-content/plugins/bdthemes-element-pack/includes/updater/plugin-update-checker/Puc/v4p5/Plugin/UpdateChecker.php(152): Puc_v4p5_Vcs_PluginUpdateChecker->requestInfo(Array)

#1 /home/cloudthe/public_html/wp-content/plugins/bdthemes-element-pack/includes/updater/plugin-update-checker/Puc/v4p5/UpdateChecker.php(251): Puc_v4p5_Plugin_UpdateChecker->requestUpdate()

#2 /home/cloudthe/public_html/wp-content/plugins/bdthemes-element-pack/includes/updater/plugin-update-checker/Puc/v4p5/Scheduler.php(109): Puc_v4p5_UpdateChecker->checkForUpdates()

#3 /home/cloudthe/public_html/wp-includes/class-wp-hook.php(284): Puc_v4p5_Scheduler->maybeCheckForUpdates()

#4 /home/cloudthe/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)

#5 /home/cloudthe/pub

**Comment by Asif2BD** [comment]
This error message clearly shows this error is causing because of another Elementor Plugin, not us, check the name after "wp-content/plugins/", that is not us!

**Comment by haniobaid** [comment]
thanks and sorry. I replied to the wrong mail

On Jun 4, 2019, at 10:36 PM, M Asif Rahman <notifications@github.com> wrote:

This error message clearly shows this error is causing because of another Elementor Plugin, not us, check the name after "wp-content/plugins/", that is not us!

**Comment by haniobaid** [comment]
Tried again, the same issue occurred. However waiting a few minutes resolved it.

Basically when all plugins were updated except Essential Addons 3.0, I update it, and then as soon as the update is completed, I check wordpress and all elementor functionality is broken. Wait a couple of minutes, check again and all is well!
