### ISSUE TITLE
Problem with the update:

### ISSUE THREAD

**Issue by ferreiratof** [rupok/essential-addons-for-elementor-lite#316]
An E_ERROR error was caused in line 11 of the file /htdocs/wp-content/plugins/essential-addons-Elementor/includes/Classes/Bootstrap.php. Error message: Trait 'Essential_Addons_Elementor Traits Shared' not found

**Comment by sabuz** [comment]
Please upgrade to latest version and let me know if this has been fixed or not.

**Comment by ferreiratof** [comment]
I solved the problem by downloading version 3.03 on the site and installing it afterwards. Thank you
 
 
 
 
> Message du 30/05/19 08:35> De : "Nazmul Islam Sabuz" > A : "rupok/essential-addons-for-elementor-lite" > Copie à : "ferreiratof" , "Author" > Objet : Re: [rupok/essential-addons-for-elementor-lite] Problem with the update: (#316)> >
> Please upgrade to latest version and let me know if this has been fixed or not.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/rupok/essential-addons-for-elementor-lite/issues/316?email_source=notifications\u0026email_token=AMGDJW6NG4UCB52LXZPESIDPX5YSVA5CNFSM4HQFOU42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWRQAWA#issuecomment-497221720", "url": "https://github.com/rupok/essential-addons-for-elementor-lite/issues/316?email_source=notifications\u0026email_token=AMGDJW6NG4UCB52LXZPESIDPX5YSVA5CNFSM4HQFOU42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWRQAWA#issuecomment-497221720", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by sabuz** [comment]
Cheers!
