### ISSUE TITLE
404: assets/admin/images/ea-logo.svg

### ISSUE THREAD

**Issue by k3x** [rupok/essential-addons-for-elementor-lite#317]
The Plugin generates HTTP-404 Errors on the following path: [...]/wp-content/plugins/essential-addons-for-elementor-lite/assets/admin/images/ea-logo.svg

Maybe ea-logo.png, or icon-ea-logo.svg would be correct? Or the file ist missing.

The only place were this file is included is in includes\Traits\Admin.php line 184.

As our webserver is configured to ban ip addresses that cause 404 errors on paths with "admin" in it, this is of high importance for us.

**Comment by sabuz** [comment]
Please upgrade to latest version and let me know if this has been fixed or not.
