### ISSUE TITLE
Essential Addons Advanced Tabs

### ISSUE THREAD

**Issue by alexwishnick** [rupok/essential-addons-for-elementor-lite#319]
When I'm editing the tabs in elementor, it's working and looks fine. Then when I get out of elementor, the tabs don't show up anymore and the text in them are just bullet points on the page. I've updated essential addons, and the previous version didn't work for me either. I cleared cache and it still doesn't work.

**Comment by sabuz** [comment]
@alexwishnick 
Can you please contact us via [live chat](https://wpdeveloper.net) so that we can investigate?
