### ISSUE TITLE
I'm sorry, but this has not been resolved. Even with the current version, here is what I'm getting:

### ISSUE THREAD

**Issue by Deleyna** [rupok/essential-addons-for-elementor-lite#320]
I'm sorry, but this has not been resolved. Even with the current version, here is what I'm getting:
![image](https://user-images.githubusercontent.com/4100767/58710812-0ed71d80-8372-11e9-9ba3-284bab4b4aad.png)

_Originally posted by @Deleyna in https://github.com/rupok/essential-addons-for-elementor-lite/issues/221#issuecomment-497720037_

**Comment by Deleyna** [comment]
Please read the previous issue because I'd asked if potentially another add-on could be interfering...

**Comment by sabuz** [comment]
@Deleyna your issue was fixed in previous update. Closing the ticket for now. Feel free to reopen if you've any issue.
