### ISSUE TITLE
EA is causing elementor widgets navigation menu to not load

### ISSUE THREAD

**Issue by punknight16** [rupok/essential-addons-for-elementor-lite#322]
EA is causing elementor widgets navigation menu to not load. I updated both plugins, went into settings and disabled everything, and cleared the cache. Still wouldn't work. Deactivating fixes the problem tho.

**Comment by sabuz** [comment]
Hi @punknight16 
Sorry to see you in a trouble. Please come on live support so that we can help you to fix your problem.
