### ISSUE TITLE
Countdown doesn't work when embedded in the page with Elementor

### ISSUE THREAD

**Issue by jitendragupta87** [rupok/essential-addons-for-elementor-lite#323]
Hi,
I have downloaded 3.0.2 version of essential addons from https://wordpress.org/plugins/essential-addons-for-elementor-lite/

But while it is added and setup the expire date for a far date, I don't see countdown gets started on the live page.

I tried disabling the countdown option in the plugin page and enable back but it didn't help.
And even tried clearing the cache: wp-admin -> Essential Addons -> Tools -> Clear Cache

Please help me to resolve this issue.

Thanks a lot in advance.

Regards,
Jitendra

**Comment by sabuz** [comment]
@jitendragupta87 I have just tested it. Seems okay for me. Can you please share URL of the page where you're trying to use countdown?

**Comment by sabuz** [comment]
@jitendragupta87 Sincce this is [duplicate ticket](https://wordpress.org/support/topic/countdown-doesnt-work-when-embedded-in-the-page-with-elementor/) I'm going to close it. Please follow that one.
