### ISSUE TITLE
Disable Essential Addons Settings page redirection After activating Essential Addons for Elementor

### ISSUE THREAD

**Issue by jaydeepnamera** [rupok/essential-addons-for-elementor-lite#327]
How can i disable redirecting Behavior when activating Essential Addons for Elementor. I don't want to redirect to Essential Addons Settings page because it affects to my theme One Click Demo Data Import installation wizard.

**Comment by sabuz** [comment]
@jaydeepnamera There is no such way right now. If your're importing bulk plugin, this plugin won't redirect.
