### ISSUE TITLE
Filterable Gallery not working on livesite

### ISSUE THREAD

**Issue by MrPressButton** [rupok/essential-addons-for-elementor-lite#328]
The filterable gallery does not work properly on my live site, when using the elementor editor the filter works just fine but on the live site version, the buttons are all visible but does not respond to clicking them.

Wordpress 5.2.1
Elementor: 1.5.3
ESS Addons: 3.0.3

Any thoughts?

**Comment by sabuz** [comment]
@MrPressButton Please share your site url

**Comment by filch** [comment]
Humm, I am experiencing the same symptoms. davefilchak.com

Wordpress 5.2.1
Elementor 2.5.16
EA Addons 3.0.5

**Comment by filch** [comment]
Clearing the cache in the Essential Addons Tools fixes it.

**Comment by MrPressButton** [comment]
Thanks for your reply's. This is my live site its the first gallery. As its stands right now the filter function works, but just had a couple of instances where it did not work.

https://www.overbyexportconsulting.com

I tried clearing the cache a couple of times. I you guys could see if it work on your end that would be great.

**Comment by sabuz** [comment]
@MrPressButton seems like a permission issue on your server. Can you please make sure **wp-content/uploads/essential-addons-elementor** has correct permission to read assets file? e.g. This file  is unreadble on your server: https://www.overbyexportconsulting.com/wp-content/uploads/essential-addons-elementor/eael-post-1701.min.js?ver=3.0.5

**Comment by MrPressButton** [comment]
Is there a way of making sure that essential-addons-elementor has the correct permissions to the assets folder, I only have ftp access to the host site.

**Comment by sabuz** [comment]
@MrPressButton Please contact our [support](https://wpdeveloper.net/support/) referring the issue id 328
