### ISSUE TITLE
testimonial slider bug

### ISSUE THREAD

**Issue by michael-jceseo** [rupok/essential-addons-for-elementor-lite#330]
after updated to 3.0.4 the testimonial slider is only showing one item on page. It shows in the editor but when viewing page it only shows one. 

When I clear cache from dashboard plugin it fixes it, but when i refresh page it goes back to one testimonial slider. 

Only happens on firefox

**Comment by sabuz** [comment]
Please contact us here: https://wpdeveloper.net/support/ . Don't forget to mention git issue id

**Comment by eladyanai** [comment]
i'm experiencing the same issue...

**Comment by sabuz** [comment]
@michael-jceseo @eladyanai This issue has been fixed. Please wait for next update
