### ISSUE TITLE
wordpress tech problem report after this update

### ISSUE THREAD

**Issue by alexandreracine** [rupok/essential-addons-for-elementor-lite#333]
Got an email after updating this addon. You can thanks Wordpress for the new fonction ;)

Une erreur de type E_ERROR a été causée dans la ligne 43 du fichier /wp-content/plugins/essential-addons-for-elementor-lite/essential_adons_elementor.php. Message d’erreur : Uncaught Error: Class 'Essential_Addons_Elementor\Classes\Bootstrap' not found in /wp-content/plugins/essential-addons-for-elementor-lite/essential_adons_elementor.php:43
Stack trace:
#0 /wp-includes/class-wp-hook.php(286): {closure}('')
#1 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /wp-settings.php(399): do_action('plugins_loaded')
#4 /wp-config.php(100): require_once('/var/www/html/w...')
#5 /wp-load.php(37): require_once('/var/www/html/w...')
#6 /wp-admin/admin-ajax.php(22): require_once('/var/www/html/w...')
#7 {main}
  thrown

**Comment by sabuz** [comment]
@alexandreracine maybe plugin files are missing form your server. Can you please reinstall and check again? Let me know if this issue fix or not.

**Comment by alexandreracine** [comment]
I deleted the plugin, added it again, and no error message.
