### ISSUE TITLE
Issue when i try to edit a page on elementor which contains an essential addon widget

### ISSUE THREAD

**Issue by rodrigo-martinez-ayala** [rupok/essential-addons-for-elementor-lite#334]
Hi Guys

Recently an update from essential addons broke my website which is now fixed, but am getting an issue when i try to edit a page which contains some Essential addon widget, it shows the safe mode of elementor and i can´t work with EA. Please i need your help.

I already clear the cache of the website and from the plugin.

**Comment by sabuz** [comment]
@rodrigo-martinez-ayala please contact us from here: https://wpdeveloper.net/support/ . Don't forget to mention your issue id on github.
