### ISSUE TITLE
PHP js MIME error prevents Advanced Tabs from switching Tabs?

### ISSUE THREAD

**Issue by beab08** [rupok/essential-addons-for-elementor-lite#335]
![js MIME error](https://user-images.githubusercontent.com/9747679/59385324-5ee7b400-8d64-11e9-9c30-f8c0002cfa06.png)

If I click on a Tab it wont switch from default tab, the only way to see tabs has been to change the default tab in the backend. I have momentarily solved this by cleaning the EA cache (and browser cache) but once I refresh the page the error is back.

When looking at the console I always get this error, translated:
> JQMIGRATE: Migrate is installed, version 1.4.1
> Script “https:// ... /essential-addons-elementor/eael-post-4336.min.js?ver=3.0.5” was loaded despite MIME-type (“text/html”) not being a valid JavaScript. 
> 
> Loading failed of <script> with source “https:// ... /uploads/essential-addons-elementor/eael-post-4336.min.js?ver=3.0.5”.

Theme: TwentySeventeen 2.2
Essential Addons for Elementor 3.0.5
Wordpress v 5.1.1 - well within the safe zone.
PHP 7.1
Elementor 2.5.16.

**Comment by sabuz** [comment]
@beab08 Can you please provide me url of your site so that I can inspect?

**Comment by beab08** [comment]
Hello sabuz,

Sure it's still not officially live but I made it live so you can have a look:
https://www.hormiga.se/blog/

**Comment by sabuz** [comment]
@beab08 I'm seeing permission error on 'wp-content/upload/essential-addons-elementor' directory. Please set it to 755, and try again.

**Comment by beab08** [comment]
What do I need to set to 755 exactly?

**Comment by beab08** [comment]
I've looked through folder rights in the assigned folder, they're already set to 755, public and group rights are set to Read-only and Run-only, no permission to Write for public and group though.

**Comment by beab08** [comment]
I've made sure everything is 755 including the files in question, the problem still persists - no changes.
