### ISSUE TITLE
element update not reflecting

### ISSUE THREAD

**Issue by ihariharanui** [rupok/essential-addons-for-elementor-lite#336]
Hi,
I have added a Woo Product category in a 2 column section. In the preview, the collection title showed the right color white which I wanted. 

1) But It did not reflect live, even after clearing/purging cache a dozen times and tried multiple browsers. I had to use a css code to enforce that in white color. 

2) Changed the background to black color. Same issue. In preview, it looks fine, but in live, it's not reflecting. 

I'm about to make a huge implementation using this add on, and this is my very first use and not working is kinda turning me off. What is the issue, and how can i avoid it in the future? Thank you.

Url: www.kraftd.com / section used: mens / womens t shirts

**Comment by sabuz** [comment]
Can you please clear elementor cache from 'Elementor > Tools > Regenerate Files' and let me know.

**Comment by sabuz** [comment]
@ihariharanui No reply for a long time! I presume that your issue has been fixed. I'm closing the issue for now. Feel free to reopen it.
