### ISSUE TITLE
Bug with Post Grid in mobile version

### ISSUE THREAD

**Issue by elementor2000** [rupok/essential-addons-for-elementor-lite#337]
T
![Screenshot_2](https://user-images.githubusercontent.com/51856595/59552511-9c308980-8f90-11e9-9509-788cc970f103.png)
hrough time there is an imposition of blocks on each other

**Comment by elementor2000** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/51856595/59552538-0cd7a600-8f91-11e9-98bd-58bc2b24f0aa.png)

**Comment by sabuz** [comment]
@elementor2000 we'll check.

**Comment by sabuz** [comment]
@elementor2000 We've fixed the issue. Please wait for the next update!
