### ISSUE TITLE
EA Pro team member widget lost settings

### ISSUE THREAD

**Issue by finid** [rupok/essential-addons-for-elementor-lite#338]
Just found out today that images I displayed on my conference website using EA Team Member widget are no longer showing. You can see the effect at https://bigdataaiconference.com and https://bigdataaiconference.com/big-data-ai-conference-speakers/.

My license is active and all other images on the website using base Elementor images are showing as intended.

So now I have to readd more about 70 images.

**Comment by finid** [comment]
Just tried to edit the images. Was able to add an image, but unable to change the default image style, so something is definitely wrong with the EA Team Member widget.

**Comment by sabuz** [comment]
@finid We've fixed a bug related to team member widget. Please wait for next update!
