### ISSUE TITLE
Trait 'Essential_Addons_Elementor\Traits\Core' not found on v3.0.5

### ISSUE THREAD

**Issue by jenessawhite** [rupok/essential-addons-for-elementor-lite#341]
Hi, I just updated to v3.0.5 on WP 5.2.2 and received the following Fatal Error.

This plugin failed to load properly and is paused during recovery mode.

`An error of type E_ERROR was caused in line 13 of the file /srv/bindings/64b05929fd254505bfa31e45479e39a1/code/wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Bootstrap.php. Error message: Trait 'Essential_Addons_Elementor\Traits\Core' not found`

**Comment by rupok** [comment]
Hi @jenessawhite please try re-installing a fresh copy of the plugin.

**Comment by jenessawhite** [comment]
Hi @rupok,
Thanks for getting back to me I have re-installed with a fresh copy of the plugin and still receive the same error
`Fatal error: Trait 'Essential_Addons_Elementor\Traits\Core' not found in /srv/bindings/5ce64b0299bc4c0eb002dedf8bb77b8c/code/wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/Bootstrap.php on line 13`

**Comment by rupok** [comment]
Hi @jenessawhite This error is not possible with the new version at all. Somehow you are installing the old version I guess. PLease create a support ticket from https://wpdeveloper.net/support/ so we can check and assist.

**Comment by sabuz** [comment]
@jenessawhite Are you still getting the error?

**Comment by jenessawhite** [comment]
@sabuz yes, and I did create a support ticket.
