### ISSUE TITLE
Polyline Option in EA Google Map not working

### ISSUE THREAD

**Issue by myBCN** [rupok/essential-addons-for-elementor-lite#347]
Hi EA Team,

I'm building a map with a Polygon of my walking tour route using the Polyline function in the EA Google Map Element. No matter what I enter the map view stays locked somewhere in Lima, Peru... My POI's are all in Barcelona, Spain and if I zoom out enough I can see that they are all there where they should be. If I switch from Google Map Type: Basic where I am at the correct location to Polyline the view immediately moves to Lima, Peru.

//Matthias

**Comment by mahafuz** [comment]
Hi there,
We are already aware of the issue and fixed it. You will get this fix in the next update of the plugin.
Thanks!
