### ISSUE TITLE
EA post Grid problems

### ISSUE THREAD

**Issue by gonzalochica** [rupok/essential-addons-for-elementor-lite#351]
Hello, EA post grid still with errors. In one of my pages, if I click in load more button a few times, some posts start to overlapse between them and the load more button 'hides' behind the posts. I've tried to give it 100 px to top margin and it takes more clicks to 'hide' the button but the posts continue overlapsing.
![Captura](https://user-images.githubusercontent.com/44378094/60949287-27cdd980-a2f5-11e9-904e-8b583ba7afae.PNG)
**www.elitinerario.es/actualidad**

![Captura2](https://user-images.githubusercontent.com/44378094/60949495-9f036d80-a2f5-11e9-94d4-cc9055051c3b.PNG)

**www.elitinerario.es/reportajes**

**Comment by gonzalochica** [comment]
Up

**Comment by morettic2015** [comment]
Same here. 

![Anotação 2019-07-31 020122](https://user-images.githubusercontent.com/11476006/62185052-3416e680-b337-11e9-85a7-3b5de2f7b9aa.jpg)

**Comment by morettic2015** [comment]
I have another ISSUE. After update plugin to the latest version, a page with more then one EA POST GRID stop working. The first one duplicate data and the second one just does not load more.

Take a look

https://parquedoslagos.com/

**Comment by khan-rafin-ahmed** [comment]
@morettic2015 

We are sorry about the inconvenience caused. We are already working on the overlapping issue with Load More Button and the issue when multiple Post Grids are used on the same page. It should be resolved very soon. I hope you understand. Thank you.
