### ISSUE TITLE
Adv Google Maps API and Licence Activation

### ISSUE THREAD

**Issue by dudzikpawel** [rupok/essential-addons-for-elementor-lite#357]
Hi, I have an issue while using Advanced google maps widget. API key is set up and every so often it drops the connection showing standard map with "for development use only" along with deactivating Essential Addons license. 

https://muirhallholidaycottages.co.uk

**Comment by mahafuz** [comment]
It seems really strange.
Could you please contact support www.wpdeveloper.net/support
