### ISSUE TITLE
Keep CSS and JS in the plugin folder ?

### ISSUE THREAD

**Issue by RomainJM** [rupok/essential-addons-for-elementor-lite#359]
Hello,

I just saw this folder: /wp-content/essential-addons-elementor.
Is this a bug or you absolutely need to create an other folder outside /wp-content/plugins/yourplugin for 1 css and 1 JS?

Thank you

**Comment by rupok** [comment]
Hi @RomainJM 

Since the assets are generated dynamically so need to place in uploads folder. We can't place within plugin folder because it will be overridden when you update the plugin. It's a common practice for dynamic assets.

**Comment by RomainJM** [comment]
Hey @rupok 

Thank you for your answer. I see, it's like /wp-content/uploads/elementor with the dynamic css generation ? So maybe in a folder like this ?

Just asking, because i'm trying to keep my code, my ui, and my setup as clean as possible, for me and for my client.

Thank you
