### ISSUE TITLE
Post Grid "Load More" Button Not Working

### ISSUE THREAD

**Issue by prhelms86** [rupok/essential-addons-for-elementor-lite#370]
In the "post grid" widget, the load more button isn't working. The website is wwwmartinopodcast.com

When you click the button, nothing happens. 

The plug-in is updated.

**Comment by suiluj** [comment]
same problem here:

junges-ermland.de

there is no console log error either.

please fix this bug.

**Comment by suiluj** [comment]
bug did not get fixed (even after recent update) @rupok

**Comment by endtoosee** [comment]
same problem with me too
