### ISSUE TITLE
Server Error 500 by update the page

### ISSUE THREAD

**Issue by amela-arades** [rupok/essential-addons-for-elementor-lite#371]
Hi,

every time when I update my page I became a 500 Server Error, when I deactivate the plugin is everything normal. I love EA for Elementor and I want to use it, so if you can help me will be very nice. I use the latest version and with the earlier was no problem. Thanks in advance.

Kind regards,
Amela Asimovska

**Comment by mahafuz** [comment]
Could you please contact us from www.wpdeveloper.net/support so that we can assist you further
