### ISSUE TITLE
Just updated to version 3.2.1 and receiving "Site is experiencing technical issues"

### ISSUE THREAD

**Issue by dbowyer** [rupok/essential-addons-for-elementor-lite#373]
Hi Guys,

I've been using your free Essential Addons for Elementor plugin, specifically the Post Grid element. You can see the dev site here: https://bubble-footie.mmandb-staging.co.uk/bubble-football/

I updated to version 3.2.1 and was no longer able to access the front end of the site, giving the message 'The site is experiencing technical difficulties'. I identified EA Elements as the cause by deactivating and reactivating plugins. I have now used WP Rollback plugin to revert back to v3.1.5 and the site is working again.

Let me know if there is anything I can do to help.

**Comment by mahafuz** [comment]
Hi there,
We are already aware of the issue and the team is working on this to fix. Hopefully, it will be fixed soon and released in our upcoming update.
Thanks.

**Comment by dbowyer** [comment]
Hi Mahafuz, thanks for you comment and best wishes to the team in solving the issue. I've just tried 3.3.1 and unfortunately knocks the whole site over, reverting to version 3.1.5 using the rollback plugin and the site is running fine.

David

**Comment by dbowyer** [comment]
Hi Guys, in further relation to this case I have had to remove the EA for Elementor plugin. A team member accidentally updated from 3.1.5 to 3.5.1 and it had a catastrophic effect on the website, I'm not sure what exactly has changed but I guess Elementor's recent addition of their post grid element has created some conflicts. Wishing you the very best and thank you for your continued efforts.

David
