### ISSUE TITLE
Unable to load Elementor Pro 2.6.8

### ISSUE THREAD

**Issue by lwwds** [rupok/essential-addons-for-elementor-lite#374]

**Comment by lwwds** [comment]
I have been trying to load Elementor Pro onto my website.  I deleted the free version so I get an error of already exists.  So I loaded the original Free plugin.  I then went to add the Pro version.  Got same error already exists in the content folder.  Went to the content folder in my cPanel, went to plugins deleted the plugin.  Went to my WP site, the plugin was gone.

**Comment by UnknownGuy123** [comment]
Instructions are simple to put PRO onto elementor. All you needed to do was upload elementor PRO and enter your license key afterwards and that is it.
