### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Yobrand** [rupok/essential-addons-for-elementor-lite#377]
Hello, I just updated your plugin and when I refreshed the website, I got this error, would you please resolve it?

Fatal error: Uncaught Error: Undefined class constant 'ICONS' in /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/essential-addons-for-elementor-lite/includes/Elements/Post_Grid.php:342 Stack trace: #0 /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/elementor/includes/base/controls-stack.php(1919): Essential_Addons_Elementor\Elements\Post_Grid->_register_controls() #1 /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/elementor/includes/base/controls-stack.php(485): Elementor\Controls_Stack->init_controls() #2 /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/elementor/includes/base/widget-base.php(160): Elementor\Controls_Stack->get_stack() #3 /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/elementor/includes/base/controls-stack.php(278): Elementor\Widget_Base->get_stack() #4 /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/elementor/includes/base/controls-stack.php(1954): Elementor\Controls_Stack->get_controls() #5 /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/elementor/includes/base/contro in /home4/mugeofrey/climaxrwanda.com/wp-content/plugins/essential-addons-for-elementor-lite/includes/Elements/Post_Grid.php on line 342

**Comment by rupok** [comment]
@Yobrand Did you updated Elementor? Are you using Font Awesome 5 or 4?

**Comment by rupok** [comment]
@Yobrand Usually this is the scenario if your Elementor is backdated. Kindly update Elementor and it will be resolved.

Thanks!
