### ISSUE TITLE
Updated to 3.3.0, now can't access WP updates page

### ISSUE THREAD

**Issue by echoridge** [rupok/essential-addons-for-elementor-lite#382]
Updated to 3.3.0 and am now unable to access the WP updates page. Doing so redirects me to the Essential Addons Settings page. Deactivating the plugin does not fix the issue. I then get the "Sorry, you are not allowed to access this page." error. The URL it's going to is .../wp-admin/admin.php?page=eael-settings when you click on Dashboard -> Updates, instead of the .../wp-admin/update-core.php that it should default to.

**Comment by Asif2BD** [comment]
Could you just clear the cache? That will do the trick.

**Comment by echoridge** [comment]
I don’t have any server caching active, but I did use the EA tools to empty all caches. That worked.

Jeff Allan
CEO & Founder

E: jeff@echoridge.io
P: 603.264.0531
W: https://echoridge.io

**Comment by Asif2BD** [comment]
@echoridge, glad it worked, I wish WordPress give us ways to do all those automatically. Please let us know if you face any issue. Could I consider it closed for this issue?

**Comment by echoridge** [comment]
Yes, it’s closed. Thanks.

Jeff Allan
CEO & Founder

E: jeff@echoridge.io
P: 603.264.0531
W: https://echoridge.io

**Comment by Asif2BD** [comment]
Nice. Please do consider rating us [here](https://wpdeveloper.net/go/rate-eae), should not take more than 30-sec. 
You are welcome, and sorry again for the brief issue it caused!
