### ISSUE TITLE
Essential Addons Overriding WooCommerce Tab

### ISSUE THREAD

**Issue by slimdesign** [rupok/essential-addons-for-elementor-lite#383]
Hi,

The essential addons page seems to be overriding the woocommerce products tab- this is happening on several sites. Please advise- it seems to be a bug. Attached image showing the page it directs you to despite clicking "woocommerce".
![Screen Shot 2019-09-18 at 09 37 51](https://user-images.githubusercontent.com/55483721/65132031-278a4280-d9f8-11e9-8f90-039c17e2baf9.png)

**Comment by rupok** [comment]
Hi @slimdesign would you kindly create a support ticket with your site details so we could investigate the issue? https://wpdeveloper.net/support/new-ticket/

Thanks!
