### ISSUE TITLE
Redirecting to wrong page

### ISSUE THREAD

**Issue by motiontide** [rupok/essential-addons-for-elementor-lite#384]
When clicking on "updates" in the backend, I always get redirected to
/wp-admin/admin.php?page=eael-settings

On another site, this happens any time I click on the dashboard link

**Comment by rupok** [comment]
Hi @motiontide Are you constantly facing this or faced this once? Would you kindly create a support ticket so we could investigate the issue? https://wpdeveloper.net/support/new-ticket/

Thanks!
