### ISSUE TITLE
EA Post Grid - Portfolio bug?

### ISSUE THREAD

**Issue by lizjuhhh** [rupok/essential-addons-for-elementor-lite#385]
Hi, I've created a portfolio in Elementor and I've used the EA Post Grid to show 3 random projects on my homepage. First when I hovered a project, there was a transparant overlay, and I could click on it to go to the project page. But since the latest update, I can't click on the projects anymore, the overlay is also gone. Can you maybe help me with this problem?

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by lizjuhhh** [comment]
Thanks, I've contacted Elementor also and the problem is already solved.
