### ISSUE TITLE
EA Smart Post List Bug after upgrade the new version (3.3.1)

### ISSUE THREAD

**Issue by sztivoo** [rupok/essential-addons-for-elementor-lite#387]
Hey Guys,

I've upgraded the new version of EA today, and now all the places where I've used the EA Smart Post List has been crushed. Can you please look after it?

Here you can see a screenshot about it: https://megoldaskozpont.com/lexikon/dopamin-fogalma/  --› https://screencast.com/t/R5hFYM4GItq 

Thanks,
sztivo

**Comment by sabuz** [comment]
Please contact us [here](http://wpdeveloper.net/support) so that we can investigate.
