### ISSUE TITLE
Load more button suddenly stops working

### ISSUE THREAD

**Issue by owentwix** [rupok/essential-addons-for-elementor-lite#388]
Hi, I just noticed that the "Load more" button stopped working on all the pages on my website. Whenever I clicked on "Load more" button, it didn't do anything. All my plugins are updated. I hope you can assist. Thank you.

You can check it on my website: owentwix.com

![EA Plugin Updated](https://user-images.githubusercontent.com/55696171/65424022-15b3ff80-de3d-11e9-926e-859a6b047d37.JPG)

**Comment by sabuz** [comment]
I've just checked your site, and seems load more working correctly.

**Comment by owentwix** [comment]
Hi, yes it’s working now. I asked assistance from EA team. It’s just
caching issue. Thanks.
