### ISSUE TITLE
Essential Addons Random Plugin Conflict

### ISSUE THREAD

**Issue by slimdesign** [rupok/essential-addons-for-elementor-lite#389]
Hello, we have had several issues with Essential Addons, where it appears to conflict with certain areas.

For example, I have had the Essential Addons settings open up when choosing "Media Library" in Wordpress, and even when deactivating and removing Essential Addons, it would still attempt to open this, resulting in a "you are not allowed to view this page".

The latest issue we have had is when we are trying to view information on a completely unrelated plugin, and it tries to open up the EA settings again. This time, I have recorded a video to show you, which you can see here: https://drive.google.com/file/d/1SQu-SaDgGXQcCp0njVDbuPBnrBCA2snr/view

Please advise, as this is putting us off using EA.

**Comment by sabuz** [comment]
We've fixed this issue. Please wait for next update.
