### ISSUE TITLE
Freeze menu for Elementor

### ISSUE THREAD

**Issue by naitsirhc007** [rupok/essential-addons-for-elementor-lite#392]
When I installed this plugin, my menu from elementor is frizzed, and no response to any click mouse.
![essentialAddonsElementor](https://user-images.githubusercontent.com/26291567/66182541-233a6800-e63b-11e9-9952-90079a143e5c.PNG)

**Comment by sabuz** [comment]
This may help: https://wpdeveloper.net/elementor-stuck-loading-screen/
