### ISSUE TITLE
EA Filtrable Gallery issues

### ISSUE THREAD

**Issue by InterGlobeTech** [rupok/essential-addons-for-elementor-lite#393]
Hi guys,

It seems there is a problem with the filtrable gallery.

Colours and typography don´t work properly.
Selectable options such us reviews and price don´t work either. 

Could you have a look?
Thanks
Santiago

**Comment by mahafuz** [comment]
Hi Santiago,
We are working on this to fix. Hopefully, it will be fixed soon and released in our upcoming update.

Thanks.
Mahafuz
