### ISSUE TITLE
Catzgory in EA post grid

### ISSUE THREAD

**Issue by sandrine-site** [rupok/essential-addons-for-elementor-lite#396]
I can't have all my catégory in EA post grid :
my catégorys: 
![image](https://user-images.githubusercontent.com/44755735/66587013-e7972500-eb89-11e9-878f-791d89200763.png)

in EA post Grid :
![image](https://user-images.githubusercontent.com/44755735/66586854-a6067a00-eb89-11e9-963f-1a5cb6c61ad5.png)
how can solve that?

**Comment by sabuz** [comment]
Thank you for reporting your issue. We're aware of this issue and going to fix this within next update. Thanks!
