### ISSUE TITLE
How to ensure assets load only on pages that use the plugin?

### ISSUE THREAD

**Issue by cagross** [rupok/essential-addons-for-elementor-lite#397]
I have the Essential Addons for Elementor plugin installed on my site.  Both it, and the Elementor plugin, are in use on only one page ([page here](https://www.horizonhomes-samui.com/construction-koh-samui/)).  But when I load my home page, there are 5 different files loaded:  3 are files from your plugin and 2 are files from the Elementor plugin ([screenshot](https://i.imgur.com/uMIXdOf.jpg)).  How can I ensure that *only* the page using Elementor downloads these files, and ensure my home page does not download these files?

I have confirmed the issue occurs even when I am logged out of WordPress.

If I deactivate your plugin, and leave only the Elementor plugin activated, the issue goes away—the Elementor CSS and JS files are loaded *only* on the page in-question, and not on my home page.  So something about your plugin is causing the home page to load all 5 files. 

I am comfortable adding my own PHP code if necessary.  

I raised this with customer support (via the website) several weeks ago, and they assured me a fix would be included in version 3.3.2.  But now that version 3.3.2 has been released, I still experience the issue. I again contacted customer support, and they referred me here.

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by cagross** [comment]
Thanks for the reply.  I just updated my dev site from plugin v3.5 to v3.6.  When I re-loaded [my home page](https://dev.horizonhomes-samui.com/), the same five files were still being loaded ([screenshot](https://i.imgur.com/QPDB0Qp.jpg)).  Thoughts?  I've cleared all caches, including browser cache.

**Comment by cagross** [comment]
@GitMubarak Any update on this issue?

**Comment by GitMubarak** [comment]
Does these files appear when you are logged in?

**Comment by cagross** [comment]
If I open the page as a non-admin, these five files are loaded on the page.  If I open the page as an admin, these five files are also loaded (along with several others).

**Comment by cagross** [comment]
Any update to this issue?

**Comment by sabuz** [comment]
Sorry for inconvenience! We've fixed the issue, and on the way to next update! FYI we're loading fontAwesome in whole site because of some compatibility issue.

**Comment by cagross** [comment]
@sabuz Thanks for the reply.  But let me see if I understand what you've said.

The issue I've described is that your plugin is loading five Elementor files on every page, even when your plugin is not in-use on the page ([screenshot](https://imgur.com/uMIXdOf)).  Three of those files are files related to Font Awesome.  Are you saying this issue will be _fully_ resolved in the next plugin update, i.e. after the update, these five files will be loaded *only* on pages that use your plugin?  Or are you saying your plugin will continue to load the Font Awesome files on every page?

**Comment by sabuz** [comment]
@cagross These five files will be loaded only on pages that use our plugin.

**Comment by cagross** [comment]
@sabuz OK sounds good.  That will be implemented on the next plugin update--correct?  If so, do you have an approximate release date?

**Comment by sabuz** [comment]
@cagross within Sunday

**Comment by cagross** [comment]
Great thanks.

**Comment by cagross** [comment]
Hello.  I see versoin 3.7 of the plugin has been released.  Was the fix for this issue included in that release?

**Comment by sabuz** [comment]
Yes! We've fixed the issue.
