### ISSUE TITLE
Cannot disable toggle button on extensions tab.

### ISSUE THREAD

**Issue by bluePixel8** [rupok/essential-addons-for-elementor-lite#398]
Hi, 

I try to disable features in the extensions tab but when I save and reload the page, the buttons enabled themselves. (Try the clear cache and reinstall the plugin still doesn't work.)

Thanks,
![Capture](https://user-images.githubusercontent.com/40011169/66648783-9c971380-ec56-11e9-8ae4-d8f6f877f0a2.PNG)

**Comment by sabuz** [comment]
We've fixed the issue. Please wait for next update.
