### ISSUE TITLE
Element "EA Post Grid": Load-More-Buttons doesn't work

### ISSUE THREAD

**Issue by lvd18** [rupok/essential-addons-for-elementor-lite#399]
Hello
I implemented the element "EA Post Grid" on my page e.g. https://inspirationen-der-welt.de/nepal/annapurna-circuit-trek/von-bhulbule-nach-jagat/

But the Button Load-More doesn't work anymore. At some point it worked but not anymore. I didnt change anything.

Please can you fix that.

Thanks in advance.
Kind regards
Lena

**Comment by CilioM** [comment]
I have exactly the same issue: On the load more Button for articles: 
Checkout the site https://vision2035.ch

**Comment by lvd18** [comment]
I did this, but it is still not working
