### ISSUE TITLE
Can’t remove “EA Tools” from the Admin Bar

### ISSUE THREAD

**Issue by jeiseman** [rupok/essential-addons-for-elementor-lite#400]
Under the the Tools tab for Essential Addons settings in the backend there’s an option that says: “Show Quick Tools in Admin Bar?”. When I turn this off it doesn’t remove “EA Tools” from the admin bar. In addition if I navigate away from the settings page and then go back to the settings page I see the setting is turned back on again. I only have two plugins, this one and Elementor. I’m using the default theme (TwentyNineteen).
Commenting out the following lines in includes/Classes/Bootstrap.php solves the problem:
`        $this->additional_settings = apply_filters('eael/additional_settings', [
            'quick_tools' => true
        ]);`
I tried adding a filter on “eael/additional_settings” but that didn’t work (maybe I’m not doing it right). Here’s what I added to my functions.php:
`function ea_adminbar_func() {
    return array();
}
add_filter('eael/additional_settings', 'ea_adminbar_func', 100);`

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by jeiseman** [comment]
Yes, the problem was.resolved in the latest version.
