### ISSUE TITLE
Load button doesn't work

### ISSUE THREAD

**Issue by MichanFIN** [rupok/essential-addons-for-elementor-lite#403]
Hello,

I'm using EA Post Timeline Element on my blog. From the beginning it didn't seem to be working well, as when clicking the button Load more (Cargar más) it started to load posts from the beginning. 

But know the problem is bigger: the button simply doesn't work. I try to click on it, but nothing happens. 

You can check it on https://michanenfinlandia.com/

Would be great if you could solve this problem soon.

Thanks!

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by MichanFIN** [comment]
> 
> 
> Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

Seems to be working again, but the other problem mentioned (starting to load from the wrong point) is still there. 

Thanks for your collaboration!
