### ISSUE TITLE
Creative Buttons - winona transition

### ISSUE THREAD

**Issue by antonzakh** [rupok/essential-addons-for-elementor-lite#407]
After the most recent update buttons containing more than 1 line of text are buggy, specifically "Winona" transition the text under "hover" effect stays uncovered. Even though the style has been fixed to cover it

**Comment by khan-rafin-ahmed** [comment]
@antonzakh, well, I tried to reproduce. It seems to be working as expected. Have you tried clearing your cache from wp-admin -> Essential Addons -> Tools? Also, clear cache from any Elementor or even from caching plugin you are using (if any)? Let me know how it goes.
