### ISSUE TITLE
Bug for new update - Removes Pics from EA Post Carousel

### ISSUE THREAD

**Issue by chicagoseogeeks** [rupok/essential-addons-for-elementor-lite#408]
The update removes all pics from the EA Post Carousel

**Comment by vgstef** [comment]
Yeah, same problem for me.

**Comment by sjuzups** [comment]
Same for me as well.  Looking for any assistance on this.

**Comment by rhcpdu13** [comment]
hi,
I have the same problem with the Post Block, the image header doesn't show pics.

**Comment by chicagoseogeeks** [comment]
Heard back from the developer.  They suggested to upgrade the PRO version to the below.  That did the trick.  Carousel post pics show correctly now.

"Update the PRO version ( 3.4.0 ) as well. For now, you can download the PRO plugin from here: https://d.pr/f/OoWpLO"

**Comment by rhcpdu13** [comment]
Thank you very much, its ok again now :)
