### ISSUE TITLE
Conflict with OceanWP - Mobile menu doesn't work

### ISSUE THREAD

**Issue by petrect** [rupok/essential-addons-for-elementor-lite#411]
With the active plugin the mobile menu on mobile devices is not working and only adds a “/#” to the end of the url. I have the Theme "OceanWP" and I don't know if the problem also occurs with other themes. 
If I disable the plugin the menu works again.
Wordpress, themes and plugins updated to the latest version available today(06 November 19).
Thanks and best regards,
Gianluca

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? If the issue still there, please provide us the page url where you are facing the problem with a screenshot.
Thank you

**Comment by petrect** [comment]
Hi, with the new update I don't see the problem. To confirm I recreated the component (news grid) but everything works fine. Thanks :)

**Comment by petrect** [comment]
Hi, with the new update I don't see the problem. To confirm I recreated the component (news grid) but everything works fine. Thanks :)
