### ISSUE TITLE
Timeline suddenly stopped working

### ISSUE THREAD

**Issue by simplicity17** [rupok/essential-addons-for-elementor-lite#412]
Maybe it was due to an update but all of the content in my vertical timeline won't show up anymore. I have the Essential Addons Pro version with the latest Wordpress and Elementor updates.

**Comment by GitMubarak** [comment]
Hi there,
Make sure you are using the latest versions of the Free ( 3.5.3 ) & Pro ( 3.4.0 ) plugins.
Note: We are having a temporary issue with the automatic update feature of the PRO version. So, for now, you have to update the PRO version manually. Check this out for help: https://essential-addons.com/elementor/docs/manually-update-essential-addons-pro/
I hope everything works fine now. Let me know if still anything wrong. 
Thanks

**Comment by sabuz** [comment]
Upgrading to latest version should fix your issue. Thanks!
