### ISSUE TITLE
EA Post Carousel not showing images after update to latest version (3.5.1)

### ISSUE THREAD

**Issue by Evergreen99** [rupok/essential-addons-for-elementor-lite#415]
I made the mistake of updating the plugin to Version 3.5.1. What used to work no longer works. 
The images disappeared. All I can see are think lines where images should be. 
 
![image](https://user-images.githubusercontent.com/39683079/68523410-a91a8600-026d-11ea-86df-bee95950b3a1.png)

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by Evergreen99** [comment]
Upgrading has not resolved the issue. This is really bad. Not sure who does QA at EA, but you definitely have a serious problem. I ended up looking for another plugin. 

Best regards,
Ismael

**Comment by vgstef** [comment]
I also have this problem with latest version and is quite embarrassing. Any updates or workaround?

**Comment by vgstef** [comment]
The new update for Pro Version 3.4.1 fixed the issue for me. Thanks!
