### ISSUE TITLE
the plugin crashes the front end

### ISSUE THREAD

**Issue by eladyanai** [rupok/essential-addons-for-elementor-lite#416]
this is how it looks great in the beckend:
https://www.screencast.com/t/odX7e2Kqsc8

this is how the homepage looks on the frontend:
https://www.screencast.com/t/LcTdQa9Jm

(this is not even using an EA element...

i have eliminated all other plugins:
https://i.imgur.com/jdMMxtF.png

i'm using the HELLO theme

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by eladyanai** [comment]
yes - this was the problem 
b.t.w - the automatic update didn't work so only when i deleted it manually and installed it fresh from your site it worked....
