### ISSUE TITLE
EA Feature list icon inner color is purple, always 

### ISSUE THREAD

**Issue by peibol382** [rupok/essential-addons-for-elementor-lite#417]
Hi, after last update inner color of icon is always purple no matter what other colour you have set. Weird. 
Thanks for the plugin
![Captura1](https://user-images.githubusercontent.com/57639168/68613266-a82c6300-04be-11ea-9b6f-21adcde995b6.JPG)
![Captura2](https://user-images.githubusercontent.com/57639168/68613267-a8c4f980-04be-11ea-942c-217b07e53432.JPG)

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by peibol382** [comment]
Hi, after upgrade to 3.6 version it works perfect again. Thanks so much!

> Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.
