### ISSUE TITLE
essential Addon is not working properly when activated

### ISSUE THREAD

**Issue by igniteddream** [rupok/essential-addons-for-elementor-lite#419]
when I recenlty updated this plugin on 13th november
my website structure changed from normal view to messy view
please fix this addon issue

**Comment by saumi785** [comment]
Same problem with my website. I have already written an email two days back to the support team, but did not get any reply so far. Now I am switching to another plugin.

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by saumi785** [comment]
Now its working fine after upgrading to 3.6.0 version.
Thanks
