### ISSUE TITLE
Prevents Elementor from producing css for styling on pages.

### ISSUE THREAD

**Issue by Chillifish** [rupok/essential-addons-for-elementor-lite#420]
Since the most recent update (I think), Elementor styling chosen (centre text in text editor) or custom CSS typed in the custom CSS box is not being generated on the front end.

Disabling this plugin causes the issue to go away.

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by Chillifish** [comment]
Yes, this seems to have fixed the issue, thanks very much.
