### ISSUE TITLE
Plugin problem with Booking Ultra Pro Appointments Booking Calendar Plugin

### ISSUE THREAD

**Issue by richie0712** [rupok/essential-addons-for-elementor-lite#421]
since Update of essential Plugin to 3.5.2 Booking Plugin doesnt work anymore!!!
when i deactivate essential it works again.
https://wordpress.org/plugins/booking-ultra-pro/
https://bookingultrapro.com/

The page I need help with: https://gesundheitspraxis-zeihen.ch/buchung/

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.
