### ISSUE TITLE
Post grid repeats posts

### ISSUE THREAD

**Issue by achpa** [rupok/essential-addons-for-elementor-lite#422]
When load more button is used in post grid; it repeats posts on the page and shows the same post 2-3 posts.

**Comment by GitMubarak** [comment]
Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

**Comment by achpa** [comment]
> Can you please upgrade to latest version and check again? Let me know if upgrading resolves your issue or not.

I've upgraded but still same issue.
