### ISSUE TITLE
Advanced tabs only work after cache cleared

### ISSUE THREAD

**Issue by ellamck3** [rupok/essential-addons-for-elementor-lite#428]
Advanced tabs only work the first time after the cache is clared, so one have to clear it every time one wants the tabs to work properly.

**Comment by shamserSuzon** [comment]
Hi there,

Are you using any cache plugin on your website? On the other hand, please, make sure you are using the latest version of the plugin. Free - 3.7.1 and Pro - 3.4.2

Looking forward to hearing from you soon. Thank you.
