### ISSUE TITLE
EA Product Grid don't show elements in columns after update

### ISSUE THREAD

**Issue by Shini-D** [rupok/essential-addons-for-elementor-lite#430]
After updating my plugins, I noticed that the EA Product Grid widget didn't show the product elements in columns anymore. I have it configured to show 3 columns but no matter how many columns I put in the widget options it only shows as 1.

I don't remember exactly which plugins I updated, but I'm currently using:

- Elementor 2.8.0
- Essential Addons for Elementor 3.6.2
- WooCommerce 3.8.1

![image](https://user-images.githubusercontent.com/37385046/70585932-c35cc200-1b93-11ea-86fc-89865ae33367.png)

**Comment by sabuz** [comment]
Upgrading to latest version should fix your issue.
