### ISSUE TITLE
EA Product Grid Problem

### ISSUE THREAD

**Issue by princ-imran** [rupok/essential-addons-for-elementor-lite#431]
EA Product Grid column option not working. Please solve this issue next update.
Thanks

**Comment by mahafuz** [comment]
Hi there,
Could you please record me reproducing your issue using a tool like this? https://www.loom.com
It helps me to quickly figure out the issue and squash it immediately.
Thanks

**Comment by sabuz** [comment]
Upgrading to latest version should fix your issue.
