### ISSUE TITLE
EA Lightbox & Modal stylesheet not being loaded

### ISSUE THREAD

**Issue by actindependent** [rupok/essential-addons-for-elementor-lite#432]
Not sure if this issue has been documented but I've found that initially the references to the stylesheet and javascript files that hides the Lightbox & Modal - 

wp-content/uploads/essential-addons-elementor/eael-post-11.min.css
wp-content/uploads/essential-addons-elementor/eael-post-11.min.js

aresn't being loaded into the head and footer of the site pages and as a result, all content within the modal is loaded directly underneath the trigger button on page load rather than being initially hidden.

When I reload the page - and this can be any page on the site initially - the file references are inserted into the code and the modal content is hidden as it should be.

Any thoughts why these files wouldn't be initially loaded?

I've managed to get round this by using a header/footer script insertion plugin to places those two files as should be but it obviously not a great solution.

**Comment by sabuz** [comment]
@actindependent Please contact us here: http://wpdeveloper.net/support/

**Comment by mahafuz** [comment]
As we have requested you to contact our support forum, we are closing this GitHub ticket for now. You can re-open it anytime. Thank you.
