### ISSUE TITLE
Facebook Pages Feed Is Broken

### ISSUE THREAD

**Issue by JohnnyTuts** [rupok/essential-addons-for-elementor-lite#433]
I've successfully created a permanent Facebook access token but everytime I load up my page with it on, the feed appears a crushed up and smash together. Please fix this asap, it's been an annoying process to get that facebook feed up and running.
![Facebook error](https://user-images.githubusercontent.com/59288111/71522094-f4dfc800-28cb-11ea-9f5a-7588b8165dae.png)

**Comment by mahafuz** [comment]
Kindly, explain your issue in detail and create a support ticket through this link: https://essential-addons.com/elementor/support/
Our Technical Support team will get back to you. Thank you.
