### ISSUE TITLE
Elementor - EA Filterable Gallery loading error

### ISSUE THREAD

**Issue by fmsdegroot** [rupok/essential-addons-for-elementor-lite#437]
<body><head>
<h2>EA Filterable Gallery</h2>
<br>

<p>Hi there,

I've spotted an issue using this extension in your plugin for Elementor.
After setting up all content and settings, I stumbled on an issue with the <b>'load more'</b> button.
Somehow it doesn't load on my live website. I couldn't find the reason why.
Maybe there's an easy fix someone's familiar with.

Let me know.

Kind regards,

S.
</p></head></body>

**Comment by sabuz** [comment]
Please contact us here: http://wpdeveloper.net/support/ and mention this issue id.

Regards!
