### ISSUE TITLE
Essentials breaks widget viewer when installed with JetWidgets For Elementor already installed

### ISSUE THREAD

**Issue by tonydehnke** [rupok/essential-addons-for-elementor-lite#439]
I have JetWidgets For Elementor already in use on my Elementor site.  Tried to install Essentials Lite and when it is activated ti breaks the widget picker in Elementor (spinner keeps spinning).  If I disable either plugin, it starts to load correctly again.

**Comment by sabuz** [comment]
Can you please [increase memory limit](https://essential-addons.com/elementor/docs/faq/increase-memory-limit-wordpress/)? Let me know if it fix your issue or not.

**Comment by tonydehnke** [comment]
That seems to have worked.. might be a good idea to add a memory check or notice in the app or when it's loaded to let users know there might be a problem..
