### ISSUE TITLE
Server Error: 400

### ISSUE THREAD

**Issue by imgraphicscmyk** [rupok/essential-addons-for-elementor-lite#440]
When trying to update pages in my Elementor created site, I've been getting Server Error code 400 preventing me from clicking "update" for the page.  I resolved this by having to deactivate the Essential Add-ons plug-in and then reactivate it -then it seemingly works okay, at least until the next time I log in to make edits.

**Comment by shamserSuzon** [comment]
Hi there,

Please, make sure you are using the latest version of the plugin. **Free - 3.7.1** and **Pro - 3.4.2**

Looking forward to hearing from you soon. Thank you.
