### ISSUE TITLE
ea filterable gallery

### ISSUE THREAD

**Issue by davelost** [rupok/essential-addons-for-elementor-lite#442]
Hey there, 

building an elementor page with ea filterable gallery, when I start to use the filter, eventually stop working and page freezes, here and example https://queensvarieties.com/alstroemerias/

**Comment by shamserSuzon** [comment]
Hi there,

I can see it's working fine: https://www.loom.com/share/92ee2f98069b40e6893ee4f89daa9226

**Comment by davelost** [comment]
Thanks for the quick reply

Yes, it works fine but when you go trough the filters a few times it
frizzes, try clicking all colors and the go back to "ALL" category,
suddenly it will crash

**Comment by shamserSuzon** [comment]
I have checked as per your given instruction but still, couldn't reproduce it: https://www.loom.com/share/32c757f0308b47e5ae7a0b99f55a86ca

**Comment by davelost** [comment]
Thanks for the video, I can see you're not having the same issue
