### ISSUE TITLE
Advanced Tabs loading in WordPress without styling and functionality

### ISSUE THREAD

**Issue by phillycc** [rupok/essential-addons-for-elementor-lite#445]
According to the Chrome inspector, the supporting JS and CSS files (required by the tabs block) are loading absolute paths to those files, but are missing my site domain.

For instance, instead of:
https://[site-domain]/wp-content/uploads/essential-addons-elementor/eael-post-[id].min.js

I am getting a path with no site domain:
https:///wp-content/uploads/essential-addons-elementor/eael-post-[id].min.js

Above, the site domain appears to be an empty string or null.

Chrome Network tab says the required files “failed” to load and hence the Advanced Tabs have no styling or functionality. If the absolute path is fixed (or a relative path is used instead), I’ve confirmed that the block works!

I’m using a lightweight minimalist theme for Elementor (Hello), but have tested it in multiple other lightweight themes. I’m also using the latest versions of WordPress and Essential Addons.

Given that this is open source, can anyone point me in the direction of those files that set the site domain values and create the absolute paths mentioned above?

**Comment by sabuz** [comment]
Hi!
It should be fixed now. If you are still suffering from this issue, feel free to reopen the issue and contact us!
