### ISSUE TITLE
EA Filter Gallery - BUG on Any Mobile browser

### ISSUE THREAD

**Issue by VladSer88** [rupok/essential-addons-for-elementor-lite#446]
Hello, 

please have a look at
www.unveiled.ro/bug

**On the first load, the galley is not loaded correctly (all the items are stacked)**
After fitlering / searching, the gallery is correctly displayed.
Issue only appears on mobile devices. 
The gallery customizing is excellent could you please have a look over this issues? 
maybe you  have some ideas. 

Best regards,
Vlad

**Comment by shamserSuzon** [comment]
Hi @VladSer88 

Are you using any cache plugin and lazy loading feature on this page? If yes, then could you please, deactivate the lazy loading and check if the problem is still there or not. Let me know how it goes.

Thank you.

**Comment by VladSer88** [comment]
Hi,
Thanks @shamserSuzon , this was the isses, i was using the lazy loading from Smush.
Problem solved now.
Have a great day,
Vlad

**Comment by shamserSuzon** [comment]
Nice to hear that your issue is solved now. Cheers!
