### ISSUE TITLE
EA Advanced Table doesn't work

### ISSUE THREAD

**Issue by hcppumpsintl** [rupok/essential-addons-for-elementor-lite#447]
Hello!!
In first place congratulations for your great plug in
I would like to ask you about a problem I have.
I am trying to put an EA Advance Table in my website, but when I put the table in the box, I can't add information to the table. 
Also, I can't import information, when I paste .cvs information and click import nothing happens.
Do you have any idea about how to solve this problem?

Thanks in advance for your help,

Best Regards,

A

**Comment by shamserSuzon** [comment]
Hi, there,

Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Then, check back. Let me know how it goes. 

If the above steps don't fix your issue then please, open a support ticket here: https://essential-addons.com/elementor/support/

Thank you.
