### ISSUE TITLE
The Visible Item option is not working properly on EA Post Carousel

### ISSUE THREAD

**Issue by Prontoshine** [rupok/essential-addons-for-elementor-lite#455]
### Re Produce

I was trying to adjust the visible post item to:

 - **6 items** for a desktop screen.

Here is the result (it displays properly)
![image](https://user-images.githubusercontent.com/17017699/74915783-641ef780-53f7-11ea-8e3e-609f59de02d7.png)

 - **3 items** for a tablet screen. (it should show **3 items** but there are **6 items**)

![image](https://user-images.githubusercontent.com/17017699/74915930-94669600-53f7-11ea-9fb6-da4944dddfee.png)

 - **2 items** for a mobile screen. (it should show **2 items** but there are **3 items** which I've set in the tablet option.)

![image](https://user-images.githubusercontent.com/17017699/74915988-a6483900-53f7-11ea-9bc8-f673946b05a3.png)

### Expectation

The widget should display the post item properly on every screen.

### Note

The plugin version I'm using below:

 - Essential Addons for Elementor version 3.8.0 
 - Essential Addons for Elementor - Pro version 3.4.2

**Comment by shamserSuzon** [comment]
Hi there,

Sorry to hear about the inconvenience. We are already aware of the issue and our developers are working on this to fix it. Hopefully, it will be fixed soon and released by the next update. Till then I would like to request you to wait a bit.

Thanks for your patience.
