### ISSUE TITLE
Plugin update changed post grid

### ISSUE THREAD

**Issue by dianeferreira13** [rupok/essential-addons-for-elementor-lite#458]
I had my posts in masonry in the post grid but when I did the plugin update it made all the images huge and stacked one on top of the other. It changed the sizes and layout. Even when I adjusted the settings it did not help

**Comment by shamserSuzon** [comment]
Hi there, 

Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Then, check back. Let me know how it goes. 

Thank you.

**Comment by SkynyCode** [comment]
> Hi there,
> 
> Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx
> 
> Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Then, check back. Let me know how it goes.
> 
> Thank you.

It worked

**Comment by dianeferreira13** [comment]
Yes that seems to have worked! Thank you so much! Should I do that after every update?

**Comment by dianeferreira13** [comment]
Actually it is happening again. It was fine and then I had a post go live this morning and it is doing it again and I have regenerated files and all that and it is still huge and not coming out in a grid.
