### ISSUE TITLE
Pricing Table Image causes notice in PHP 7.4 when not set

### ISSUE THREAD

**Issue by J-Nagle** [rupok/essential-addons-for-elementor-lite#459]
When using PHP 7.4  with Essential Addons For Elementor Lite 3.8.1, Pricing Table elements without images will generate a notice. The output is below.

```
Notice: Trying to access array offset on value of type null in <path>/plugins/essential-addons-for-elementor-lite/includes/Elements/Pricing_Table.php on line 1837
```

Please implement a fix for this. I suggest the following.

```php
		if(!empty($pricing_table_image)){
			$pricing_table_image_url = Group_Control_Image_Size::get_attachment_image_src( $pricing_table_image['id'], 'thumbnail', $settings );
		}
```

I am using Roots' Bedrock framework, and haven't been able to figure out how to suppress notices with it. My local environment is running XAMPP and PHP 7.4.2, but they probably do not affect this issue.

**Comment by sabuz** [comment]
@J-Nagle Thanks for reporting the issue, we've fixed the issue, please wait for next release.
