### ISSUE TITLE
Changes in EA Advanced Data Table

### ISSUE THREAD

**Issue by elementor2000** [rupok/essential-addons-for-elementor-lite#462]
Hello.
Please make it possible to edit the EA Advanced Data Table in the table itself, and not in the list on the left.
With a large number of points of content, you can easily get confused.

![image](https://user-images.githubusercontent.com/51856595/75442437-275b7f00-5968-11ea-867e-a9bd333afb26.png)

Thank you for your attention.

**Comment by shamserSuzon** [comment]
Hi there, 

You are using the EA Data Table widget and we don't have such feature here. But we have launched a new widget called 'EA Advanced Data Table' where you will have this feature that you are looking for. Please, find the doc here: https://essential-addons.com/elementor/docs/advanced-data-table/

Thank you.

**Comment by elementor2000** [comment]
Thank you very much, that's great.
But I can’t edit it: I can’t add text, a column, nothing.

![image](https://user-images.githubusercontent.com/51856595/75715252-c7e9d000-5cd5-11ea-9fc5-350ccc36214c.png)

**Comment by elementor2000** [comment]
all functions included

![image](https://user-images.githubusercontent.com/51856595/75715348-ee0f7000-5cd5-11ea-9cef-cff3fb8815b4.png)

**Comment by shamserSuzon** [comment]
Hi there,

Which version of the EA plugin you are using now? Please, make sure you are using the latest versions of the Free ( **3.8.2** ) & Pro ( **3.5.1** ) plugins.

Also, please, try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Then, check back. Let me know how it goes. 

Thank you.

**Comment by elementor2000** [comment]
Thanks.
Followed all instructions.
The latest version of the program is installed.
But still I can’t edit the table. I can’t write anything into it, add a column or row.
I can only change the color of the background.

![image](https://user-images.githubusercontent.com/51856595/75899279-000f2100-5e44-11ea-8caa-8c999bd581de.png)

![image](https://user-images.githubusercontent.com/51856595/75899331-10bf9700-5e44-11ea-9f74-702ec026d559.png)

![image](https://user-images.githubusercontent.com/51856595/75899386-203ee000-5e44-11ea-996b-b00622ae8299.png)

**Comment by shamserSuzon** [comment]
Hi there,

I think your issue needs a deep investigation.

Please, open a support ticket here by explaining the issue: https://wpdeveloper.net/support/

Thank you.

**Comment by elementor2000** [comment]
I get it. thanks

**Comment by shamserSuzon** [comment]
Nice to hear that your issue is now resolved. Cheers! :)
