### ISSUE TITLE
EA Post Grid release 3.8.2.

### ISSUE THREAD

**Issue by Batedeira** [rupok/essential-addons-for-elementor-lite#464]
Just updated the Plugin to release 3.8.2.

The lay-out settings in The EA Post Grid are not working correclty. We have set up the post summary in 3 columns. However after the update, the posts are displyes in one column (whilst the number of columns in the lay out settings remains on 3)

**Comment by Batedeira** [comment]
Already found the solution; EA Dashboard > Tools > Regenerate Asssets

**Comment by shamserSuzon** [comment]
Nice to hear that your issue is resolved now. Cheers! :)
