### ISSUE TITLE
EA Post Grid after update Is no longer working correctly

### ISSUE THREAD

**Issue by ruarkvallen** [rupok/essential-addons-for-elementor-lite#465]
It should display the post in 4 columns, but it's not anymore. 
Cause seems to be the title, it's just displaying in one straight line and not breaking into multiple lines. 

I tried regenerating assets as well, and it's still broken. Tried it twice and refreshed. Closed and opened the page.

**Comment by shamserSuzon** [comment]
Hi there,

It seems like caching issue. Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://prnt.sc/r3b588

If the issue still persists, please try clearing your browser cache or try another browser too.

Let me know how it goes. Thank you.
