### ISSUE TITLE
Essential Addons Post Grid bug

### ISSUE THREAD

**Issue by HevansWrites** [rupok/essential-addons-for-elementor-lite#466]
I was using the EA plugin with no issues but I've encountered a problem with the post grid option. It was formatting correctly in a grid but it now only shows in a line on the left side of the screen. I have cleared all my caches on the site and on my browsers and it is still happening. It also happens when I'm on an incognito browser.

Halp!

**Comment by shamserSuzon** [comment]
Hi there, 

Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Then, check back. Let me know how it goes. 

Thank you.
