### ISSUE TITLE
Translation of EA Data Table

### ISSUE THREAD

**Issue by vgstef** [rupok/essential-addons-for-elementor-lite#467]
I'm using the EA Data Table on our website. We use WPML to have translation from French to English.

Unfortunately, WPML doesn't detect any strings from the table. so I can't translate it. Could you make this widget translation ready?

Thanks!

**Comment by shamserSuzon** [comment]
Hi there,

Currently, EA Data Table is not compatible with WPML. Hopefully, it will be implemented soon.

Thank you.
