### ISSUE TITLE
EA Content Ticker v2.7.3 issues

### ISSUE THREAD

**Issue by rootnevtv** [rupok/essential-addons-for-elementor-lite#47]
After updating v2.7.3 Content Ticker widget bugs appeared:
1. When navigation arrows are on, two arrows are shown - first is strange big blue and second that selected in settings.
2. Content is placed little off center instead aligment left.
3. No sliding or fading between posts.

**Comment by rupok** [comment]
Hi @rootnevtv I guess you are having cache issue. Clear your cache and hard refresh the page. It should be fine.

**Comment by sabuz** [comment]
I presume your issue was fixed since no reply for a long time. So, I'm closing this ticket. Feel free to reopen if you have any issue.
