### ISSUE TITLE
Error after migrating site to new server

### ISSUE THREAD

**Issue by Tekamba** [rupok/essential-addons-for-elementor-lite#472]
I had done a site for a client under my development setup (tempdomain.com/clientsubdomain) format. I made the site live today by copying database and files over to the new server and everything worked well. However the page that I had used the EA Team Member tool does not allow me to open the page for editing unless I disable the EA Addons for Elementor Pro plugin.
I tried to rebuild the CSS and a few other resets but it still won't allow me to edit the page. I could possibly create it again from scratch but it would be nice to find out what happened and why I can't open it for editing.
 - Greg

**Comment by shamserSuzon** [comment]
Hi there,

It sounds very strange! Actually, it is tough to answer you properly without seeing the issue live. Could you please record me reproducing your issue using a tool like this? https://www.loom.com 
It helps me to quickly figure out the issue and squash it immediately. 

Thank you.
