### ISSUE TITLE
Fatal/Critical Error

### ISSUE THREAD

**Issue by KiraATD** [rupok/essential-addons-for-elementor-lite#473]
Fatal error: Default value for parameters with a class type hint can only be NULL in /home/allthatsgood/public_html/wp-content/plugins/essential-addons-elementor/includes/Template/Content/Post_Carousel.php on line 12
There has been a critical error on your website.

Learn more about debugging in WordPress.

**Comment by rupok** [comment]
Hi @KiraATD 
Are you using the Pro version? In that case, make sure both plugins are up to date.
If you still see the error, kindly create a ticket from here with your site access - https://wpdeveloper.net/support/new-ticket/

**Comment by KiraATD** [comment]
Yes, when I turn on the pro version it gives that error. I disabled both and it stopped. I removed both and did a new install but it continued to give that error. The only thing that stopped the error was to turn Post Carousel off, within the settings, then turned the pro version back on and it didn't give the error.

**Comment by rupok** [comment]
Hi @KiraATD we have just released EA Pro v3.6.2. Please update and let me know if that fixes the issue.

**Comment by KiraATD** [comment]
it fixed it! thank you for your assistance in this
