### ISSUE TITLE
Elementor PRO not working

### ISSUE THREAD

**Issue by saumi785** [rupok/essential-addons-for-elementor-lite#474]
My elementor has not been working since morning and when I disabled Essential Add-ons, it works.
Please look into the matter as I am using some Essential Add-ons widgets on my website and I can't disable the plugin for long.

**Comment by khan-rafin-ahmed** [comment]
@saumi785,

Hi, there. That's rather strange. Are you seeing any particular error in the console when you have Essential Addons enabled? It could be memory limit issue as well. Have you tried increasing your PHP Memory Limit to 256M or 512M and check back?

Besides, for additional info, could you please enable the debug mode. You can do this by opening `wp-config.php` and adding the below code just above /* That's all, stop editing! Happy blogging. */ :

```define('WP_DEBUG', true);```

When you revisit the page, you should have some error output describing the issue in more detail.

Let me know how it goes. Thank you!
