### ISSUE TITLE
Content Ticker widget broken on Elementor Archive page.

### ISSUE THREAD

**Issue by zmalsberg** [rupok/essential-addons-for-elementor-lite#475]
The CSS gets all screwed up, stretches badge across the whole column, content pushes to next line, does not scroll, weird blue arrows appears on either side of column along with the default back/forward buttons. I tried taking out all custom css and most plugins, no dice. I like the way the plugin works, but it breaks only on archives page's header for some odd reason.

**Comment by Fabian570** [comment]
No entienfo a que te refieres con tu comentario

**Comment by khan-rafin-ahmed** [comment]
Hi @zmalsberg @Fabian570,

We have found the issue with archive pages and we are preparing a new release within next couple of days. It will fix the issue of yours. Thank you for your patience.
