### ISSUE TITLE
All EA sections not showing any of the styles applied

### ISSUE THREAD

**Issue by coderguider** [rupok/essential-addons-for-elementor-lite#477]
All EA sections added on my site have reset to default on the live site but are still as they were while editing in Elementor.

I searched for assistance on the Support forum on Wordpress.org.

You can view that [here](https://wordpress.org/support/topic/all-ea-sections-not-showing-any-of-the-styles-applied/)

**Comment by sabuz** [comment]
Are you still suffering from this issue? If yes, Go to Elementor > Tools > Regenerate Assets might help.
