### ISSUE TITLE
Shared.php safe_protocol function wrong

### ISSUE THREAD

**Issue by DenisHoppe** [rupok/essential-addons-for-elementor-lite#478]
Hello,

the function  safe_protocol is function correctly:

 public function safe_protocol($url)
    {
        if (is_ssl()) {
            $url = wp_parse_url($url);
            //$url['scheme'] = 'https';
            return $this->unparse_url($url);
        }
        return $url;
    }

**Parameters $url:**  
is array(1) {
  ["path"]=>
  string(71) "/wp-content/uploads/4/essential-addons-elementor/eael-post-6948.min.css"
}

and Wordpress can not wp_parse_url($url); no host found at param $url. So i have errors on css and JS load. 

Thanks for fix this Bug.

Best regards Denis

**Comment by sabuz** [comment]
@DenisHoppe what is the value of $url parameter you're passing into safe_protocol function?

**Comment by DenisHoppe** [comment]
@sabuz ok we have install a WP multi site. The param $url is not include a host in array only a path string without host. If the function add the schema https than rendered the new url https:///wp-content/uploads/4/essential-addons-elementor/eael-post-6948.min.css 

This is not correctly and get an error in Browser. And all my java scripts or css not work. At the moment we changed the class every after plugin update. 

Thanks for fix the  bug.
