### ISSUE TITLE
Uncaught ReferenceError: elementorModules is not defined

### ISSUE THREAD

**Issue by Webmatthieu** [rupok/essential-addons-for-elementor-lite#479]
Hello, I can't edit my pages with elementor when the plugin is activate. There is an error message on elementor : Preview Could Not Be Loaded
Inside my console when I use the preview debug : 

Uncaught SyntaxError: Unexpected token ')'
Uncaught ReferenceError: elementorModules is not defined
    at Object.<anonymous> (125bc.js:3)
    at __webpack_require__ (125bc.js:3)
    at Object.<anonymous> (125bc.js:3)
    at __webpack_require__ (125bc.js:3)
    at Object.<anonymous> (125bc.js:3)
    at __webpack_require__ (125bc.js:3)
    at 125bc.js:3
    at 125bc.js:3

Maybe cause by the last update of elementor?

**Comment by rupok** [comment]
Hi @Webmatthieu 

It doesn't look like an issue related to Essential Addons rather Elementor itself.

Thanks!

**Comment by Webmatthieu** [comment]
I find the problem: When I remove the commentaries in js files with litespeed plugin, there is an error conflict with essential-addons-for-elementor-lite

**Comment by Fabian570** [comment]
> Hello, I can't edit my pages with elementor when the plugin is activate. There is an error message on elementor : Preview Could Not Be Loaded
> Inside my console when I use the preview debug :
> 
> Uncaught SyntaxError: Token inesperado
> ')' Uncaught ReferenceError:
> elementorModules no está definido en Object. (125bc.js:3)
> **al webpack_require** (125bc.js:3)
> en Object. (125bc.js:3)
> **al webpack_require** (125bc.js:3)
> en Object. (125bc.js:3)
> en **webpack_require** (125bc.js:3)
> en 125bc.js:3
> en 125bc.js:3
> 
> ¿Quizás causa por la última actualización del elementor?
