### ISSUE TITLE
Bug in the last update

### ISSUE THREAD

**Issue by Rafaelbarlev** [rupok/essential-addons-for-elementor-lite#482]
Hello EA support.
I’m using Fluent Forms (as part of EA in Elementor) and after the last update the plugin is not keeping the design of the Form (changes in colors and so on) so I downgraded to the previous version of EA.
Thank you,
Rafael

**Comment by sabuz** [comment]
Hey there,
Can you please make sure that you are using the latest versions of Essential Addons Free 4.0.4 on your website? Your issue should be resolved by now. Make sure to regenerate assets from Essential Addons -> Tools as well.
If you are still facing issue, please contact our support here for further assistance: wpdeveloper.net/support
Thank you!
