### ISSUE TITLE
Error in essential-addons-for-elementor-lite for Contact Form 7

### ISSUE THREAD

**Issue by lucasroblox** [rupok/essential-addons-for-elementor-lite#486]
I can't change the size of the box
![Captura de pantalla (1)](https://user-images.githubusercontent.com/63747663/79379063-afa3dc80-7f34-11ea-9827-2917ce249ef4.png)
![Captura de pantalla (2)](https://user-images.githubusercontent.com/63747663/79379071-b3376380-7f34-11ea-8cd4-b6886f6fcb82.png)

Can u fix that? Thank u

**Comment by Fabianfer** [comment]
Y para que es mi hermano disculpa
