### ISSUE TITLE
STOP activating by default new EA elements on each update

### ISSUE THREAD

**Issue by oscarhenao** [rupok/essential-addons-for-elementor-lite#488]
You guys definitely have the best add-on for Elementor. Your product is great and very useful and friendly, but **CAN YOU PLEASE STOP ACTIVATING new Elements/Extensions/Tools/Etc. automatically on each update!** It is a pain you know where to have to disable them every time.

This practice makes the site slower and load lots of code that is not and will not be used unless the designer/developer is informed of it existence + likes it + needs it. 

How about taking users - right after the update - to a screen with a description of the update and the new elements, or perhaps, a bar at the top of the updates screen (like most of the other plugins) announcing the changes and with a link to the details of the update.

**Comment by khan-rafin-ahmed** [comment]
@oscarhenao,

Thank you for the suggestion. However, if you don't use our element, they are not loaded on your website at all. So, there's no chance of site getting slower with that case. Do you face the assets generating of the newly added elements despite you are not using 'em?

Thank you!
