### ISSUE TITLE
Conflict with elementor 

### ISSUE THREAD

**Issue by AzzaAlbelushi** [rupok/essential-addons-for-elementor-lite#494]
Hello ,

essential addons for elementor conflict with elementor pro

**Comment by khan-rafin-ahmed** [comment]
@AzzaAlbelushi,

What sort of conflict are you facing? Essential Addons is actually fully compatbile with Elementor PRO. Can you share a screenshot?

Thanks

**Comment by AzzaAlbelushi** [comment]
when i activate it . Elementor Stop working.So i Deactivate it .

**Comment by khan-rafin-ahmed** [comment]
@AzzaAlbelushi 

It sounds like PHP Memory Limit issue. Make sure that you got enough PHP Memory Limit on your website like 256M or 512M. Thank you!

**Comment by AzzaAlbelushi** [comment]
Thank you, let me check that

**Comment by AzzaAlbelushi** [comment]
Alright, Elementor work fine now, Thank you
