### ISSUE TITLE
Filterable Gallery Not Working

### ISSUE THREAD

**Issue by itsturkb** [rupok/essential-addons-for-elementor-lite#495]
I am trying to use the Filterable Gallery on Elementor under Essential Addons; however, it does not seem to be working properly and I cannot figure out why. 

From what I have read on the internet, I go to "Essential Addons" in the Dashboard and then click on the "Tools" and finally click on "Regenerate Assets". When I do this, the Filterable Gallery works but as soon as I refresh the page, it does not work again. 

How can I solve this issue quickly?

**Comment by itsturkb** [comment]
The only part which does not work properly is the "List Items"; so basically when I click on the different list items such as "European Partners" or "National Partners", it is supposed to filter the rest out and only shows those under these titles. It does this after I "Regenerate Assets" but right after I click refresh, it goes back to not working again.

**Comment by khan-rafin-ahmed** [comment]
@itsturkb,

That's strange. Can you please share your page URL with us so that we can check?

Besides, you can contact our support team here for further queries: wpdeveloper.net/support

Thank you!
