### ISSUE TITLE
product grid is not working properly 

### ISSUE THREAD

**Issue by suratkart9** [rupok/essential-addons-for-elementor-lite#496]
i have applied product grid but it is not working properly 
i have tried everything please check the below link 
https://suratkart.com/vegetables-fruits/

**Comment by sabuz** [comment]
@suratkart9 Are you taking about [this](https://tinyurl.com/y9v99zpr)?

**Comment by suratkart9** [comment]
Hi,
Thankyou for your valuable reply,
Here I attached the screenshot,
The problem is when I use product grid,it doesn't work properly,
I have applied 3 products in 1 row but it shows only 1 product also with
zoomed image of product which is not looking good

Thank-you
9898822143

**Comment by sabuz** [comment]
@suratkart9 Maybe you forget to attach screenshot. [This is what I'm seeing](https://tinyurl.com/yctuhcsw). Grid seems okay to me.

**Comment by suratkart9** [comment]
Here is the screen shot
As you can see in screen shot I have applied columns - 3, product count-
3,offset-3 after applying this also
After updating it shows only one product in 1 line which is looking very
bad , please help me with this

https://suratkart.com/vegetables-fruits/

**Comment by khan-rafin-ahmed** [comment]
@suratkart9,

Please contact us here: wpdeveloper.net/support

We need to investigate your website. Thank you
