### ISSUE TITLE
Having Problems whit the counter and feature list

### ISSUE THREAD

**Issue by Alberto090** [rupok/essential-addons-for-elementor-lite#497]
It looks completely different in Elementor than in the launch website. Those ones present failures in the visuals that make it look much less attractive
![92DCFE0A-8AD7-43FB-8F14-D6AF105B6180](https://user-images.githubusercontent.com/64055408/81373835-52c6bc80-90c3-11ea-9a5f-4fb40b8d3b18.jpeg)
![BB7116E2-45BB-4FD6-AF57-EDA3117DD982](https://user-images.githubusercontent.com/64055408/81373844-55c1ad00-90c3-11ea-8f27-d3bb9ad3e7ed.jpeg)

**Comment by Alberto090** [comment]
![B7EF1E1A-01FB-45D2-9CE0-2A2349328F31](https://user-images.githubusercontent.com/64055408/81374781-ac2feb00-90c5-11ea-8a32-6bc5bcd83d0e.jpeg)

**Comment by sabuz** [comment]
@Alberto090 Can you please share your site url?

**Comment by Alberto090** [comment]
iucrqroo.com

**Comment by sabuz** [comment]
I'm seeing some [errors](https://tinyurl.com/y7o7wexc) in console regarding contact from 7. Can you please fix these and check if this solves your issues?

**Comment by Alberto090** [comment]
How do I do that?

**Comment by sabuz** [comment]
@Alberto090 As you are in a touch with our support team, I'm closing this ticket.
