### ISSUE TITLE
Can't add any widget on page?

### ISSUE THREAD

**Issue by ManojKTomar** [rupok/essential-addons-for-elementor-lite#504]
Can't add any widget from elementor on page? even with new page? can modify and save. 
![EA](https://user-images.githubusercontent.com/40908595/82827182-1f11d200-9ecc-11ea-950d-ab6cee6d05e2.PNG)

**Comment by rupok** [comment]
Hi @ManojKTomar Can you confirm you are using the latest version v4.0.0? If you are using Pro vetsion, you need to upgrade to v.4.0.0 too. Let me know your version number.

**Comment by ManojKTomar** [comment]
Hello using latest version. same issue with elementor widget also?

Version 4.0.0




Thanks / Kind Regards


Manoj Kumar

Business-Led Technology Partner

Driving & Leading Digital & IT Strategy to achieve Business outcomes

Business Focused and Value Co-creation Prioritization

Information Technology (IT)


ManojKTomar@Outlook.com<mailto:ManojKTomar@Outlook.com> |+91 981 8970 815

https://www.linkedin.com/in/manojk365/

________________________________

**Comment by rupok** [comment]
Are you sure it's causing by Essential Addons? Did you try disabling it? It sounds like Elementor issue.

**Comment by ManojKTomar** [comment]
Thanks, resolved. was caching issue.
________________________________
