### ISSUE TITLE
Advanced Accordion problem on latest version

### ISSUE THREAD

**Issue by syedkamal92** [rupok/essential-addons-for-elementor-lite#506]
hi, i had update essential addons to the latest version today.

but i noticed a problem with Advanced Accordion that i created before

the text on tab was misalign ..

please double check this

**Comment by andresvuy** [comment]
Same problem here

**Comment by khan-rafin-ahmed** [comment]
@syedkamal92 @andresvuy,

Can you guys please share a screenshot? Thank you!

**Comment by Cosmin05** [comment]
Hi,

I'm having the same problem - all the Accordion tab titles get realigned to the center.

I can't find any way to align them to left, as they were by default.

![image](https://user-images.githubusercontent.com/43205637/84152080-7b482a80-aa64-11ea-8015-929a8049f934.png)

**Comment by andresvuy** [comment]
Sorry, I dont have screenshot because I rolled back intermediately to the previous version. But is the same problem like Cosmin05.

**Comment by sabuz** [comment]
Couldn't reproduce your issue. Can you please contact [support team](https://wpdeveloper.net/support/) so that we can investigate further?
