### ISSUE TITLE
Update to 4.0.2 broke custom fields override with PressForward plugin

### ISSUE THREAD

**Issue by publicmedievalist** [rupok/essential-addons-for-elementor-lite#507]
I use the PressForward plugin to aggregate articles from around the web onto my site (https://pressforward.org/). It uses a custom field ("item_author") to pull the article's author, and then behind the scenes overrides the post author with this custom author field (https://pressforwardadmin.gitbooks.io/pressforward-documentation/content/user-manual/posting-nominated-items-to-wordpress.html). This was working just fine in EAE lite 4.0.1, but the most recent update seems to have broken this. This is a _major_ problem for the site as it now looks like I'm claiming credit for other people's work.

**Comment by khan-rafin-ahmed** [comment]
@publicmedievalist,

That's strange. Can you kindly provide me a screenshot? Besides, please contact our support here: wpdeveloper.net/support

We will look into this and get this resolved. Thank you!

**Comment by publicmedievalist** [comment]
No problem-- I pinged the support (and opened a ticket). The page in question is here: https://www.devilshistorians.com/in-the-news/

**Comment by publicmedievalist** [comment]
I just wanted to say that this issue was patched in 4.0.3. Thank you for being so quick and responsive!
