### ISSUE TITLE
[EA Advanced Accordion] Text align issue in tab titles

### ISSUE THREAD

**Issue by Cosmin05** [rupok/essential-addons-for-elementor-lite#510]
Hi,

I think the last update made all the Accordion tab titles get realigned to the center.

![image](https://user-images.githubusercontent.com/43205637/84151739-1260b280-aa64-11ea-8d55-e37126254a33.png)

I can't find any way to align them to left, as they were by default.

Can you please help with this issue?

Thank you!

**Comment by sabuz** [comment]
We couldn't reproduce the issue. Can you please contact our [support team](https://wpdeveloper.net/support/) so that we can investigate further.
