### ISSUE TITLE
Post carousel isn't displayed correctly

### ISSUE THREAD

**Issue by jonathangagnon13** [rupok/essential-addons-for-elementor-lite#511]
I added the post carousel from EA pro and it worked fine until I made the latest update. It showed 4 posts on desktop screen, 2 on tablet and 1 on mobile. After the update, it only shows 1 post on desktop and 2 on mobile although all the settings are still correct. I tried rollback to the previous version of EA and it didn't fix the issue. I even tried rollback to the previous version of Elementor and it didn't do anything either.

**Comment by sabuz** [comment]
Upgarding to latest version should fix your issue.
