### ISSUE TITLE
Content/Button Alignment in Call to Action Box

### ISSUE THREAD

**Issue by DavidCouns** [rupok/essential-addons-for-elementor-lite#512]
The content and button will not align to centre in the call to action box since Astra Theme update a week ago.  Any ideas?

**Comment by sabuz** [comment]
Can you please make sure that you are using the latest versions of Essential Addons Free 4.0.4 on your website? Your issue should be resolved by now. Make sure to regenerate assets from Essential Addons -> Tools as well.
If you are still facing issue, please contact our support here for further assistance: wpdeveloper.net/support
Thank you!
