### ISSUE TITLE
Button problem

### ISSUE THREAD

**Issue by akaeidalakib** [rupok/essential-addons-for-elementor-lite#514]
This is design pick ![image](https://user-images.githubusercontent.com/66782803/84385005-b0917b80-ac10-11ea-9e11-63b3ae570501.png)
 But why don't show button properly? Please check this issue. Button name is Creative Button
![image](https://user-images.githubusercontent.com/66782803/84385323-34e3fe80-ac11-11ea-97c0-f60d5b086d4d.png)

**Comment by sabuz** [comment]
Can you please contact our [support team](http://wpdeveloper.net/support/) so that we can assist?
