### ISSUE TITLE
Feature List Connector 

### ISSUE THREAD

**Issue by mkorte4008** [rupok/essential-addons-for-elementor-lite#516]
Appears that with one of the recent updates the connector lines are visually above the icons. 
<img width="713" alt="Screenshot at Jun 14 14-07-56" src="https://user-images.githubusercontent.com/44909349/84601890-22eca080-ae49-11ea-9bb1-6f7e16c3364b.png">
This occurs when you select framed w/ the classic look of the list.

**Comment by sabuz** [comment]
Clearing cache should fix your issue.
