### ISSUE TITLE
Error of icon fonts

### ISSUE THREAD

**Issue by AdriWaxman** [rupok/essential-addons-for-elementor-lite#521]
I have an error with the icon fonts of the calendar component. Don't load correctly. I use the Astra Theme with Elementor and the plugin wp-optimize for optimization.

While I find the solution, I hide the icons.
Thanks!

**Comment by sabuz** [comment]
Can you please share your site url so that we can investigate? For further assistance please [contact our support team](http://wpdeveloper.net/support/) so that we can help you.
