### ISSUE TITLE
stopped working after updating elementor

### ISSUE THREAD

**Issue by axlrider** [rupok/essential-addons-for-elementor-lite#56]
After updating the elementor plugin, the essential addons stopped working with it

**Comment by rupok** [comment]
Hi @axlrider Can you be a bit more specific? Which element stopped working? We always test with beta version of Elementor. That mean if something released, we have tested with that version already. Let me know what are you facing.

Thanks!

**Comment by axlrider** [comment]
Well, if i disable "essential addons" and i try edit pages with elementor, it works perfectly.
But, if i enable essential addons, when i try edit pages with elementor, doesn't work anymore and show me this message: Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

**Comment by rupok** [comment]
It's usually a cache issue and comes from caching plugin. You can try clearing cache. Also might cause if you have insufficient memory. You can check memory from Elementor > System Info and make sure they are at least recommended values. 

Also you can disable the elements you are not using on your site from **Elementor > Essential Addons > Elements**. It will decrease the payloads. Let me know how it goes.

Thanks!
