### ISSUE TITLE
EA Filterable Gallery images not open in same tab

### ISSUE THREAD

**Issue by coolrawat90** [rupok/essential-addons-for-elementor-lite#59]
Hello Team, 

I am facing the problem in Filterable Gallery images not open in the same tab.

when we click on the image that is redirecting in the image URL, Please suggest the best advice.

Thanks,
Deepak!

**Comment by rupok** [comment]
Hi Deepak

Can you show me the issue with your URL?

Thanks!

**Comment by coolrawat90** [comment]
Sure!

Please find the URL:

http://webinventus.com/homepage

you can find the gallery in the footer.


-----
*Regards*
Deepak Singh Rawat
*+91 7838181658*
[image: http://in.linkedin.com/in/deepaksinghrawat1]
<http://in.linkedin.com/in/deepaksinghrawat1>[image:
https://twitter.com/deepaksinnghraw]
<https://twitter.com/deepaksinnghraw>[image:
https://www.facebook.com/rawatgm] <https://www.facebook.com/rawatgm>[image:
https://www.youtube.com/channel/UChfzGZ1i88V3oF2O0NSkcvA]
<https://www.youtube.com/channel/UChfzGZ1i88V3oF2O0NSkcvA>[image:
https://www.pinterest.com/rawatgm] <https://www.pinterest.com/rawatgm>

**Comment by rupok** [comment]
Hi @coolrawat90 

I have tested with several setup and can't replicate such issue. I am not sure why it's happening on your site but I can have a look if you can initiate a live chat from https://essential-addons.com/elementor/ and provide me a temporary access.

Thanks!

**Comment by coolrawat90** [comment]
Hellol Team,

 I would like to inform you, Your updated version is not working properly.
it's hiding website content. I am deactivating for some time. Please,
Action on that. I will wait for your improvisation.







Thanks,
Deepak!


-----
*Regards*
Deepak Singh Rawat
*+91 7838181658*
[image: http://in.linkedin.com/in/deepaksinghrawat1]
<http://in.linkedin.com/in/deepaksinghrawat1>[image:
https://twitter.com/deepaksinnghraw]
<https://twitter.com/deepaksinnghraw>[image:
https://www.facebook.com/rawatgm] <https://www.facebook.com/rawatgm>[image:
https://www.youtube.com/channel/UChfzGZ1i88V3oF2O0NSkcvA]
<https://www.youtube.com/channel/UChfzGZ1i88V3oF2O0NSkcvA>[image:
https://www.pinterest.com/rawatgm] <https://www.pinterest.com/rawatgm>

**Comment by soyJSus** [comment]
Could you solve this problem?

**Comment by coolrawat90** [comment]
What a jock 😁! Awesome Customer support system.👍😁👍
-----
*Regards*
Deepak Singh Rawat
*+91 7838181658*
[image: http://in.linkedin.com/in/deepaksinghrawat1]
<http://in.linkedin.com/in/deepaksinghrawat1>[image:
https://twitter.com/deepaksinnghraw]
<https://twitter.com/deepaksinnghraw>[image:
https://www.facebook.com/rawatgm] <https://www.facebook.com/rawatgm>[image:
https://www.youtube.com/channel/UChfzGZ1i88V3oF2O0NSkcvA]
<https://www.youtube.com/channel/UChfzGZ1i88V3oF2O0NSkcvA>[image:
https://www.pinterest.com/rawatgm] <https://www.pinterest.com/rawatgm>
