### ISSUE TITLE
500 Error upon activation

### ISSUE THREAD

**Issue by lauras** [rupok/essential-addons-for-elementor-lite#66]
Note that this was on Wordpress.com (Business Plan site), if that makes a difference. I installed release 2.7.5. As soon as I activated the plugin, my entire site and admin area when to a 500 error.

I got support to disable this plugin, and everything came back. I am trying .com to avoid sysadmin duties. The downside is I don't have any access to the server logs. The support person said they had seen this twice now with this plugin, but that's anecdotal. Sorry, I don't have more to offer.

If you'd like my system stats and other plugins, I can give you that.

**Comment by sabuz** [comment]
@lauras Upgrading to latest version should fix your problem. Cheers!
