### ISSUE TITLE
Blank page when activating plug-in

### ISSUE THREAD

**Issue by OscarTheSprollie** [rupok/essential-addons-for-elementor-lite#79]
Hi,

The page is blank when I try to edit the page using elementor pro. I'm using the 'Hello Theme' and elementor pro. When I turn the plug-in off, the page opens fine in elementor.

The only other plug-ins activated are Akisment, Elementor, Elementor Pro and Pods.

Any suggestions would be greatly appreciated as this plug-in looks like it would have features that I would find really useful.

**Comment by rupok** [comment]
Hi there,

If you are using the free version, can you try the updated version and check?

Thanks!
