### ISSUE TITLE
EA interfering with Media Carousel in Coverflow mode

### ISSUE THREAD

**Issue by cfmx** [rupok/essential-addons-for-elementor-lite#86]
after installing EA, Media Carousel's Coverflow mode works only in editing mode.
after deactivating & deleting, MC-C worked both in editing and production.

this is from my Elementor's System Info:
== Debug ==
	Errors: 
		TypeError: An invalid argument supplied as multiple control value
			at https://blog.<url>/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.2.1 - 2:8206
			2018-09-05 02:49 +00:00
			category: InvalidElementData
			tag: Element `undefined` got <https://blog.<url>/wp-content/plugins/essential-addons-for-elementor-lite/assets/img/accordion.png> as `eael_accordion_bg` value. Expected array or object.
			x 8 times

[system-info-blog.url-08-09-2018.txt](https://github.com/rupok/essential-addons-elementor-lite/files/2363419/system-info-blog.url-08-09-2018.txt)

**Comment by sabuz** [comment]
@cfmx Upgrading to latest version should fix your problem! Cheers!
