### ISSUE TITLE
 Page not found

### ISSUE THREAD

**Issue by jeffersonarantesgmail** [rupok/essential-addons-for-elementor-lite#89]
My Website is servuti.com.br

Essential Addons is not working together with the Elementor. When creating a new page or editing with the Elementor, the message: PAGE NOT FOUND.

I had to disable Essential Addons to be able to edit with the Elementor.

Please help me.

Thank you.

jeffersonarantes@gmail.com

**Comment by LizethGalvez** [comment]
He tenido problemas para abrir mi pagina en elementor, hasta que vi tu mensaje desactive Essential Addons y por fin abrió.

**Comment by sabuz** [comment]
Hi there!
Upgrading to latest version should fix your issue. Cheers!
